### ISSUE TITLE
[sign_in_with_apple] "Execution failed for task ':app:checkDebugDuplicateClasses'" on Android

### ISSUE THREAD

**Issue by daniellampl** [aboutyou/dart_packages#100]
After integrating `sign_in_with_apple` into my existing Flutter project I receive the following error when running the application on Android in debug and release mode:

`What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-20.0.jar (com.google.guava:guava:20.0) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)`

Adding the package with the latest version to my `pubspec.yaml` is enough to make the application crash. I also followed the step in the ReadMe Setup section. I've installed the latest version stable Flutter version (1.17.3) on my machine.

`pubspec.yaml` file:

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.2
  get_it: ^4.0.2
  flutter_dotenv: ^2.1.0
  logger: ^0.9.1
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  flutter_svg: ^0.17.4
  flutter_secure_storage: ^3.3.3
  device_info: 0.4.2+4
  shared_preferences: ^0.5.7+2
  json_serializable: ^3.3.0
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.7
  image_picker: ^0.6.6+4
  dio: ^3.0.9
  http_parser: ^3.1.4
  cached_network_image: 2.2.0+1
  photo_view: ^0.9.2
  intl: ^0.16.1
  get: ^2.5.6
  firebase_analytics: ^5.0.14
  share: ^0.6.4+3
  sign_in_with_apple: ^2.5.0

dev_dependencies:
  build_runner: 1.10.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

**Comment by HenriBeck** [comment]
Hey, @daniellampl would you be able to create a repo with a reproduction? I checked our example project and it still works with `1.17.3`.

It could be a conflict with a different package that depends on some other version of an android package.

https://github.com/aboutyou/dart_packages/issues/96#issuecomment-642901789 lists a potential fix, but getting a proper reproducible example would be great.

**Comment by daniellampl** [comment]
That's it. I wasn't be able to find this previous Issue.

In my case add `implementation the 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'` fixed it for me.

**Comment by tp** [comment]
Thanks for sharing the solution.

Will close this then as resolved.

**Comment by creativecreatorormaybenot** [comment]
Just for reference: the line of course goes without the `the` 😄 

```gradle
implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
```

**Comment by daniellampl** [comment]
> Just for reference: the line of course goes without the `the` 😄
> 
> ```groovy-gradle
> implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
> ```

Of course! Thanks for sharing!
