### ISSUE TITLE
[sign_in_with_apple] Unsure of what to add in redirectUri for Android

### ISSUE THREAD

**Issue by sahebsingh416** [aboutyou/dart_packages#101]
Hi,

I am not able to determine what should I add in redirectURI so that I can be redirected to my app after signing in with my apple ID in the browser.

Thanks.

**Comment by tp** [comment]
Hey @sahebsingh416,

the redirect URI should point to your backend and must be configured in Apple's portal under the allowed callback URLs.

The purpose of the redirect URL is to open your Android app using an `intent://` deep link.

This project provides and example server as well as a description on the behavior in https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#server

Please re-open if you have any further questions around this or some suggestions to make the docs more clear in this regard.

**Comment by neha-madhini** [comment]
Hi,

my project name is 'flutter_app_setup'
my package identifier is 'com.example.flutter_app_setup'
what to include in the redirect uri?

**Comment by tp** [comment]
@neha-madhini Unless you're using Firebase, you need to set up your own server to receive the redirect links as described here: https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#server

That endpoint is then the one to use for the redirect URI parameter.

**Comment by rikai-trongpq** [comment]
> @neha-madhini Unless you're using Firebase, you need to set up your own server to receive the redirect links as described here: https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#server
> 
> That endpoint is then the one to use for the redirect URI parameter.

What if I use Firebase?

**Comment by tp** [comment]
> What if I use Firebase?

@rikai-trongpq Then they provide you with a redirect URL to use. See this clip for an example https://youtu.be/XV1rZ-JO-o4?t=604 or refer to their docs.

(I know that some people here use Firebase successfully, but I have never done the integration myself so am not knowledgeable about every detail of the setup.)

**Comment by HenriBeck** [comment]
> What if I use Firebase?

@tp & @rikai-trongpq, you need a custom server to work with our package even if you use Firebase. The return URL of Firebase doesn't provide the same functionality as we expect, so we can't use it.  

We will also never add support for it as it's a system not in our control, and we also don't force people to use Firebase; this package shouldn't expect you to use a particular service.
