### ISSUE TITLE
[sign_in_with_apple] Getting just the private email

### ISSUE THREAD

**Issue by tamirrab** [aboutyou/dart_packages#107]
I need to get the real email to connect with my user, but I’m getting only the private email even if I selecting the real email

**Comment by HenriBeck** [comment]
@tamirrab I just checked and the code works as expected and I get my correct email. 

Could you please elaborate on your exact problem and share some of the code you are using?

**Comment by tamirrab** [comment]
This is my code,
For some reason I never get the real email:

My code:

```Future<void> handleSignInWithApple(BuildContext context) async {
  FirebaseUser user;
  try {
    final AuthorizationResult result = await AppleSignIn.performRequests([
      AppleIdRequest(requestedScopes: [Scope.email])
    ]);

    switch (result.status) {
      case AuthorizationStatus.authorized:
        AppleIdCredential appleCredential = result.credential;

        OAuthProvider oAuthProvider =
            new OAuthProvider(providerId: "apple.com");
        final AuthCredential credential = oAuthProvider.getCredential(
          idToken: String.fromCharCodes(appleCredential.identityToken),
          accessToken: String.fromCharCodes(appleCredential.authorizationCode),
        );

        AuthResult authResult = await _auth.signInWithCredential(credential);

        user = authResult.user;

        await _getUserByEmail(context, user.email);
        break;

      case AuthorizationStatus.error:
        print("Sign in failed: ${result.error.localizedDescription}");
        break;

      case AuthorizationStatus.cancelled:
        print('User cancelled');
        break;
    }
  } catch (e) {
    PlatformException error = e;
    debugPrint(" bug tamir: ${error.message}");
  }
}
```

**Comment by HenriBeck** [comment]
You are not using our library. Either please switch to our library and see if it then works, or file an issue at correct Github Repository.

Therefore I'm closing this issue for now.

**Comment by tp** [comment]
For reference the new issue is here https://github.com/tomgilder/flutter_apple_sign_in/issues/49

@tamirrab If that issue can't be resolved, I encourage you to try this package, there is also some information on how to integrate with Firebase, so that's definitely something that is working for many people.

Might it be that the e-mail is never updated after any one has been associated with the app? Then you could try to disassociate the app under the Apple ID settings.
