### ISSUE TITLE
Giving "invalid_grant" on validate with Apple Servers

### ISSUE THREAD

**Issue by alexaf2000** [aboutyou/dart_packages#108]
Hi!

I'm actually using sign_in_with_apple 2.5.1, using only the iOS version, and I'm doing the sign in function as the example says, and once the user is logged with apple and receives the credentials data I'm giving the authentication code and sending to my app own server, and once there, my servers will communicate with Apple Server's as the usual way on the endpoint "https://appleid.apple.com/auth/token" sending as parameters the next:
- client_id: com.nameoftheapp.service
- client_secret: (.p8 file parsed to JWT Token as the documentation says)
- grant_type: authorization_code
- code: (the autentication code received from the client app on user logged in)

When I do this request from the server or even with postman the result I give is: "invalid_grant".
The curious thing here is that I think that maybe can be the client_secret, maybe i made a bad conversion from the p8 file key but i tried to change just a letter from the client_secret but the error changes to "invalid_client".

Maybe just doing as the code of the example is not enough? I will be very thankful if someone can help.

**Comment by HenriBeck** [comment]
Hey @alexaf2000 

Sorry, we won't be able to help here. We did not develop the backend which is used at our company and the code you are needing help with is out of the scope of this library.

Note that an authorization code is only valid for 5 minutes and to me it seems you are missing a parameter:
![Screenshot 2020-07-06 at 19 13 16](https://user-images.githubusercontent.com/8514706/86620524-c0f10800-bfbc-11ea-9846-63ffe695cb86.png)
https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens

**Comment by alexaf2000** [comment]
The issue was solved, and I think is related with your documentation also.

In fact, to help other people, the error was that i was validating the iOS apple sign in sending as client_id the ServiceID instead of the bundleID, this issue was also repeating on the client_secret (because there you also need to insert your bundleID). And of course the redirect_uri I remember that is not necessary for the iOS sign in.

Also thank you @HenriBeck for you reply !
