### ISSUE TITLE
[sign_in_with_apple] can't get user credentials

### ISSUE THREAD

**Issue by gabrielfgularte** [aboutyou/dart_packages#109]
Hi there. I'm trying to add this plugin to my app. I've done all the steps described in the README but I'm encountering some unnexpected behaviours:

1 - When I hit the button the "apple login screen" is very different from that one in README:
[My Apple Login](https://i.imgur.com/UUltckO.jpg)

2 - Touching "Continue", it asks for my Face ID to start session and it shows an "Ok" after the face check. No Apple ID description wall nor Name and Email (real or fake/hidden) wall are shown.

3 - Once it come back to my app, all user credentials are missing. Here is my code (the same code in the README tutorial):
```
Future<void> _handleAppleSignIn() async {
    final credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
    );
    print(credential);
  }
```
The output for `print(credential)` is:
```
AuthorizationAppleID(000364.429629a550054b5d9f8941d592fff520.1342, null, null, null, authorizationCode set? true, null)
```

Also, `credential.email`, `.givenName`, `familyName` are `null`.

Could you help me? Thanks in advance :)

**Comment by HenriBeck** [comment]
@gabrielfgularte The `email`, `givenName`, and `familyName` are only available on the first sign in. 

You can revert the access for your app [here](https://appleid.apple.com/account/manage). That will allow you to simulate a completely new sign up for your own user.

**Comment by gabrielfgularte** [comment]
> @gabrielfgularte The `email`, `givenName`, and `familyName` are only available on the first sign in.
> 
> You can revert the access for your app [here](https://appleid.apple.com/account/manage). That will allow you to simulate a completely new sign up for your own user.

Thank you! Solved!

**Comment by nydlmaster** [comment]
> here

could you elaborate please. where exactly i can revert? the link doesn't have any app section.

**Comment by yuanxintaxon** [comment]
is there a method in package to manually revert? E.g logout
