### ISSUE TITLE
How can I get A unique, random(temp) email address??

### ISSUE THREAD

**Issue by wangjacsi** [aboutyou/dart_packages#114]
In Apple document, 
[https://support.apple.com/en-us/HT210425](https://support.apple.com/en-us/HT210425)

Following the document: 
If users choose Hide My Email,  
A unique, random email address is created, so your personal email address isn't shared with the app or website developer during the account setup and sign in process. This address is unique to you and the developer and follows this format: <unique-alphanumeric-string>@privaterelay.appleid.com

My app is using an email address for ID so this is required! 
After getting the credential by this package, my app route new page which requests user's data especially Email.
(if users choose Hide My Email, app requests email in this page)
Because of this process, I got rejection from Apple.  How can I solve this? 
In Document, when  user hide their own email in process, random and unique email is generated right?
Can I get this email from this package? 
Is there any other solution? 

Rejection message:
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed that your app requires users to register with personal information that is not directly relevant to your app’s core functionality. Specifically, the following fields are required but do not appear to be directly relevant to your app’s core functionality:

- Email info required after sign in with Apple.

Next Steps

To resolve this issue, please either remove all required fields that are not relevant to the app or make those fields optional. Information requested during registration must be relevant to the features the app provides.

**Comment by HenriBeck** [comment]
@wangjacsi you get the email from the user in the [AuthorizationCredentialAppleID.email](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/authorization_credential.dart#L77), but you also need to provide the `AppleIDAuthorizationScopes.email` to the [getAppleIDCredential](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/sign_in_with_apple.dart#L79)

**Comment by wangjacsi** [comment]
@HenriBeck 
I can't get the email always, I mean if user selects "Hide My Email" in this process, 
I receive a null-valued email address rather than a valid one.
My app After confirming that the email address value is normal and not null, decide whether or not to show the email field in the request form of the registration page. But this process is why Apple has not passed the approval review.

![apple_login_error](https://user-images.githubusercontent.com/5095201/87329410-d85a6300-c571-11ea-8d81-1e9b2781f4fc.png)


this is my code:
`else if (type == 'apple') {
      try {
        final credential = await SignInWithApple.getAppleIDCredential(
          scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
          ],
        );

        print(credential);

        var user = {
          'id': credential.userIdentifier,
          'username': '${credential.givenName} ${credential.familyName}',
          'nickname': '${credential.givenName} ${credential.familyName}',
          'email': credential.email,
          'photo': '',
          'type': 'apple',
        };
        final check = await _socialUserCheck(user, 'apple');

        return {'user': user, 'check': check};
      } catch (e) {
        // Google Firebase Event : GFE
        await MyApp.analytics.logEvent(
          name: 'error_occur_event',
          parameters: <String, dynamic>{
            'name': 'social_provider_error',
            'type': type == null ? '' : type,
            'message': e.toString()
          },
        );

        throw (e);
      }
    }`

**Comment by HenriBeck** [comment]
@wangjacsi as described in the comment of the `email` field,  it is only available on the first sign in and not subsequent logins.

You can revert the access for your app [here](https://appleid.apple.com/account/manage). That will allow you to simulate a completely new sign up for your own user.

**Comment by wangjacsi** [comment]
I got the email by parsing token.

print(credential);
print(parseJwtHeader(credential.identityToken));
print(parseJwtPayLoad(credential.identityToken));


`Map<String, dynamic> parseJwtPayLoad(String token) {
  final parts = token.split('.');
  if (parts.length != 3) {
    throw Exception('invalid token');
  }

  final payload = _decodeBase64(parts[1]);
  final payloadMap = json.decode(payload);
  if (payloadMap is! Map<String, dynamic>) {
    throw Exception('invalid payload');
  }

  return payloadMap;
}`



`Map<String, dynamic> parseJwtHeader(String token) {
  final parts = token.split('.');
  if (parts.length != 3) {
    throw Exception('invalid token');
  }

  final payload = _decodeBase64(parts[0]);
  final payloadMap = json.decode(payload);
  if (payloadMap is! Map<String, dynamic>) {
    throw Exception('invalid payload');
  }

  return payloadMap;
}`

**Comment by HenriBeck** [comment]
@wangjacsi I guess this works as well, but you can access the email through the `email` property as well.

Closing this issue as it's solved
