### ISSUE TITLE
Using Firebase instead of the custom server

### ISSUE THREAD

**Issue by premtemp1** [aboutyou/dart_packages#120]
Hello,
  We are using firebase as out backend server.  Your readme talk about "Glitch" server. I don't want to create a 3rd party server. How can I do the same with Firebase. Specifically ,the "callbacks/sign_in_with_apple"..

Thanks for your help

**Comment by HenriBeck** [comment]
Hey @premtemp1 

We will not directly support using the Firebase Auth handler.
If you don't want to build this small server, you will need to check if the Firebase Auth Flutter Package has support for Sign in with Apple.

**Comment by timautin** [comment]
It is possible to setup Apple Sign In and FirebaseAuth, using Firebase as a backend. sign_in_with_apple plugin is not necessary, nor the custom Glitch backend.
Tutorial here: https://www.geewax.org/flutter-sign-in-with-apple

Would be nice to add a note to the README for Firebase users ;)
