### ISSUE TITLE
[sign_in_with_apple] Auth Error

### ISSUE THREAD

**Issue by Lanch92** [aboutyou/dart_packages#121]
SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))

**Comment by HenriBeck** [comment]
@Lanch92 please provide more info on what you are trying to do and the setup of your code. Also please look into the XCode console if there are more detailed error logs.

**Comment by spookymodem** [comment]
@Lanch92 I received the same error today and fixed it by opening my project in XCode, selecting "Signing and Capabilities", and adding the "Sign in with Apple" capability

**Comment by HenriBeck** [comment]
@spookymodem Thanks for the tip which @Lanch92 could check. I also suspect a configuration issue on your side @Lanch92, so please make sure everything is set up as explained in the README.

**Comment by Lanch92** [comment]
@spookymodem Thank you, I have added the "Sign in with Apple" capability to release mode, but not debug. I fixed it by adding the "Sign in with Apple" capability to debug model.@HenriBeck now，can close this issue
