### ISSUE TITLE
[sign_in_with_apple] Null Identifier with iOS and Firebase Auth

### ISSUE THREAD

**Issue by spookymodem** [aboutyou/dart_packages#122]
I'm using `sign_in_with_apple` along with the boiler-plate code below, and things are mostly working. My problem is that the call to `_firebaseAuth.signInWithCredential(credential)` is creating a firebase account that has a null identifier. The result I am consistently getting is the creation of a new user account in Firebase, and this user account is given a valid UID but a null identifier.

In the code below, the functions `SignInWithApple.getAppleIDCredential()` and `oAuthProvider.getCredential()` execute without error to generate the AuthCredential object, and that object is passed to `_firebaseAuth.signInWithCredential()`, which creates a new Firebase user, again without error. But when I look up the new account, it should have the user's email address as the identifier of the new account, but instead it has an empty string.

```
  Future<FirebaseUser> signInWithApple() async {
    final credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ]);

    OAuthProvider oAuthProvider =
    new OAuthProvider(providerId: "apple.com");

    final AuthCredential authCredential = oAuthProvider.getCredential(
      idToken: credential.identityToken,
      accessToken: credential.authorizationCode
    );

    await _firebaseAuth.signInWithCredential(authCredential);
    return _firebaseAuth.currentUser();

  }
```

**Comment by HenriBeck** [comment]
@spookymodem are you sure you are using our package?

```dart
final AuthorizationResult result = await AppleSignIn.performRequests([
      AppleIdRequest(requestedScopes: [Scope.email, Scope.fullName])
    ]);
```

This doesn't look like the code from our package.

**Comment by spookymodem** [comment]
@HenriBeck Apologies. That code was from another attempt using a similar library. The code is updated.

**Comment by HenriBeck** [comment]
@spookymodem just for clarification, this issue happens on iOS or Android?

If the `email` is correctly provided in the credential you get back, I'm don't think it's an issue with this library. Did you try decoding the `identityToken` and looking at the values of the token for any missing fields?

**Comment by spookymodem** [comment]
@HenriBeck I think you are right. It seems like the problem is not with the library. Please feel free to close this issue.

**Comment by HenriBeck** [comment]
@spookymodem, if you find a fix for the issue of the integration, feel free to share it here, so when other devs run into this issue, they can find a fix here.

I am closing this issue because our library is exposing the data correctly.
