### ISSUE TITLE
Don't call main activity to hide custom tab

### ISSUE THREAD

**Issue by Aqua-Ye** [aboutyou/dart_packages#124]
On Android, once the Apple Sign-In is successful, the plugin (callback activity) will call `triggerMainActivityToHideChromeCustomTab` to launch the main activity, with clear top flag, which will close the chrome custom tab, but also any other activity in-between (in my case the Settings activity).
Is there a way to prevent that?

**Comment by Aqua-Ye** [comment]
Closing because I found a way to prevent that, by overriding the `startActivity` method in the binding activity.

**Comment by tp** [comment]
@Aqua-Ye So you had to fork this to make it work?

As this is for Flutter, I assume most people will just have a single activity open, but if this becomes a recurring issue on Android we can think about how to solve it in the core to only restore as far as the "opening activity" (maybe there's a way to capture that better).

**Comment by Aqua-Ye** [comment]
No I just override the method that was called for starting the main activity. In my case, it's the flutter activity that hosts the flutter view.
