### ISSUE TITLE
[sign_in_with_apple] Revoke social network

### ISSUE THREAD

**Issue by macabeus** [aboutyou/dart_packages#127]
Following the item 5.1.1 on [AppleStore Guidelines](https://developer.apple.com/app-store/review/guidelines/):
> The app must also include a mechanism to revoke social network credentials and disable data access between the app and social network from within the app. 

But I can't found any method on `sign_in_with_apple` package to revoke a login with Apple. Is it possible to do that?

**Comment by HenriBeck** [comment]
@macabeus As far as I'm aware there is nothing to do on our side.

The idea is to log out the customer from your internal system, e.g. removing the user's session from your server.

In case you are polling the apple servers once a day for the validity of the refresh token, you will also need to stop it.
For more information, see here: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user
