### ISSUE TITLE
Fail to build appbundle 

### ISSUE THREAD

**Issue by gemy21ce** [aboutyou/dart_packages#128]
After adding the plugin flutter fails to build appbundle for android!

Error:
R8: Program type already present: com.google.common.util.concurrent.ListenableFuture
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

**Comment by ivanesi** [comment]
Build fails with this: 
```
What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
1 exception was raised by workers:
java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-20.0.jar (com.google.guava:guava:20.0) and jetified-listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)
```

**Comment by HenriBeck** [comment]
@gemy21ce Please provide logs of what exactly failed and the version of our plugin and flutter.

**Comment by HenriBeck** [comment]
@gemy21ce Please try https://github.com/aboutyou/dart_packages/issues/100#issuecomment-645302522 as a fix.

**Comment by gemy21ce** [comment]
Worked for me, thanks.
