### ISSUE TITLE
Got SignInWithAppleAuthorizationError AuthorizationErrorCode.unknown but previously working fine

### ISSUE THREAD

**Issue by muhrahmatullah** [aboutyou/dart_packages#130]
I got this error when trying to sign in using apple : 

`flutter: SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))`

I've read here #121 & #110 

And already implemented the fixed by adding  "Sign in with Apple" capability inside xCode project. it is weird because previously it works and a couple day later it gave me this error maybe because I'm adding new dependency? here are my list of dependency, in case there is a conflict:

```
  cupertino_icons: ^0.1.2
  provider: ^4.1.3
  graphql_flutter: ^3.1.0-beta.7
  gql: ^0.12.3
  flutter_bloc: ^5.0.0
  flutter_inappwebview: ^4.0.0+4
  meta: ^1.1.8
  youtube_player_flutter: ^7.0.0+7
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.16.1
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  build_runner: ^1.10.0
  shared_preferences: ^0.5.7+3
  google_fonts: ^1.1.0
  package_info: ^0.4.1
  progress_dialog: ^1.2.4
  url_launcher: ^5.5.0
  cached_network_image: ^2.2.0+1
  double_back_to_close_app: ^1.2.0
  dio: ^3.0.9
  sign_in_with_apple: ^2.5.2
```

added sign in with apple cabapility

<img width="865" alt="Screen Shot 2020-08-10 at 20 32 33" src="https://user-images.githubusercontent.com/13805354/89782920-b213ed00-db48-11ea-9559-40f932d57fbb.png">

Thanks in advance

**Comment by muhrahmatullah** [comment]
got it working again by revoke the apple id that I'm using for testing here: https://appleid.apple.com/account/manage
question: is this also going to happen in production release?

**Comment by nerder** [comment]
Another interesting way of solving this, that worked for me while working on the simulator is well explained here: https://github.com/invertase/react-native-apple-authentication/issues/9#issuecomment-670096191

By removing the simulator from the list of trusted devices you will be able to make Apple sign-in working again.

Hope it will help some people.

**Comment by jngbng** [comment]
Yet another way of solving this.

Setting > Apple ID > Password & Security >  (may be asked two factor authentication) > Go back to App > Try again.

(I guess apple id session on simulator is expired and AppleSignIn framework might not handle it correct way.)

Hope it will help some people.
