### ISSUE TITLE
I can't go back to the app after logging in to Apple

### ISSUE THREAD

**Issue by kelvinperea** [aboutyou/dart_packages#132]
Hello,

I am implementing your library with Firebase, this problem happens to me when testing on a real Android device in debug mode (I haven't tested it on iOS).

I did the Apple setup, Glitch and all the steps as stated in the documentation. In addition to the configuration to work with Firebase  #91 

The problem I have is that once I log into Apple, it doesn't get redirected to my app. Instead, the following screen appears and it does nothing else.

![image](https://user-images.githubusercontent.com/52806593/90341873-13184680-dfc9-11ea-8064-20c41f44c332.png)

There are no console errors that reflect a code problem.

I would appreciate it very much if you know the reason for this behavior.

Note: The application is in development and I don't have any version in the Google Play development console yet.

**Comment by HenriBeck** [comment]
@kelvinperea My best guess is that something is wrong with the redirect on the server or how it is configured in the app.

Client configuration: https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#your-app

**Comment by kelvinperea** [comment]
Thank you very much, apparently that was the problem. During setup, I apparently confused some variable that led to this strange behavior.

It works perfectly with iOS and Android integrated with Firebase.

Again, thank you very much!
