### ISSUE TITLE
Sign in in android device FAILED

### ISSUE THREAD

**Issue by boxingnguyen** [aboutyou/dart_packages#133]
After sign in with Apple I to open app again by universal link with token. It works on simulator. 
But in device after sign in with apple it back to app (not open app again by universal link) and return exception `AuthorizationErrorCode.canceled` `The user closed the Custom Tab`

I configure redirect url like that `https://xxxxcallbacks/sign_in_with_apple`  and universal link is https://xxxx/callback/sign_in_with_apple?id_token=xxxxx&name=xxxxxx

**Comment by HenriBeck** [comment]
@boxingnguyen can you verify that the redirect properly works and the intent is opened? You should see logs for the intent in the adb logs.

Also the redirect URL and universal link do not match, they have a type `callbacks` vs `callback`

**Comment by boxingnguyen** [comment]
I found the reason because config schema in android manifest not same as schema in redirect URL
` <activity android:name="com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback" android:exported="true">
          <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data android:scheme="signinwithapple" />
            <data android:path="callback" />
          </intent-filter>
        </activity>`
