### ISSUE TITLE
Compatibility ios 13.6

### ISSUE THREAD

**Issue by AllanCoinaski** [aboutyou/dart_packages#134]
Hello,

Does the plugin have compatibility with ios 13.6?

We are not able to run, we just put the plugin on the premises and when starting the emulator, it stays with the black screen.
And there is no error, just the black screen. On other iOS the app works.

Allan Coinaski

**Comment by tp** [comment]
Hey @AllanCoinaski,

for me it works just fine with iOS 13.6.

Is any stand-alone repro you could share?

**Comment by AllanCoinaski** [comment]
> Hey @AllanCoinaski,
> 
> for me it works just fine with iOS 13.6.
> 
> Is any stand-alone repro you could share?

Hello @tp 

It's really weird.

Can I share with you via Google Drive?

**Comment by tp** [comment]
Yeah sure, my e-mail is in the Git logs here :)

**Comment by AllanCoinaski** [comment]
> Yeah sure, my e-mail is in the Git logs here :)

Hi,

Did you receive the link?

The file found in the code in question is: lib/screens/login_screen.dart

‌SignInWithApple () method

But remembering that just adding ‌ sign_in_with_apple: ^ 2.5.2 in pubspec has already left the black screen.

Allan Coinaski.

**Comment by AllanCoinaski** [comment]
Hello @tp 

I had to create a new project for the plugin to work. But I don't know why it was not working before, since only the puglin was placed in the pubspec.

Anyway thank you!
