### ISSUE TITLE
Getting "The Requested Action is Invalid" with Apple Sign in with Firebase callback

### ISSUE THREAD

**Issue by CharlesCCC** [aboutyou/dart_packages#135]
Today I get the example app set-up and configured with my Firebase App.

After I login with Apple Sign in, then it suppose to redirect but I got the `The Requested action is Invalid` error.

here is my configure

```
              onPressed: () async {
                final credential = await SignInWithApple.getAppleIDCredential(
                  scopes: [
                    AppleIDAuthorizationScopes.email,
                    AppleIDAuthorizationScopes.fullName,
                  ],
                  webAuthenticationOptions: WebAuthenticationOptions(
                    // TODO: Set the `clientId` and `redirectUri` arguments to the values you entered in the Apple Developer portal during the setup
                    clientId: 'com.myapp',
                    redirectUri: Uri.parse(
                      'https://com.myapp.firebaseapp.com/__/auth/handler',
                    ),
                  ),
                  // TODO: Remove these if you have no need for them
                  // nonce: 'example-nonce',
                  // state: 'example-state',
                );
```

Any help will highly appreciated, please let me know if there is anything else needed.

**Comment by HenriBeck** [comment]
@CharlesCCC we are not supporting the Firebase Callback handler. For the plugin to function on Android you will need a small custom server that handles the redirect back to the App.

For the server and android setup have a look in our README: https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#server

After setting everything up according to the README, you can authenticate against Firebase with the code described here:https://github.com/aboutyou/dart_packages/issues/91#issuecomment-642380267

**Comment by CharlesCCC** [comment]
@HenriBeck Thank you for the quick reply and detailed help information.  I believe your solution will work, but I do wondering why we are not supporting the Firebase Callback handler ? Do we have plan to support it in the near future ?

**Comment by HenriBeck** [comment]
@CharlesCCC because not everyone is using Firebase, and this is a package that shouldn't make assumptions about which provider you are using. If you want to have a plugin that supports the Firebase Callback Handler, you should look into the `firebase_auth` plugin.
