### ISSUE TITLE
[sign_in_with_apple] Nothing happen after enter a correct password

### ISSUE THREAD

**Issue by chunlee-thong** [aboutyou/dart_packages#136]
i input a correct password and click continue then nothing happen, but if i input a wrong password, the form will reset

Flutter stable: 1.20.0, Iphone X 11 pro simulator

**Comment by urmatt** [comment]
Same issue on iOS 13.6

**Comment by HenriBeck** [comment]
@urmatt @chunlee-thong before we can look into these, we would need a full reproduction example and some logs from XCode and generally more info about this.

Note that with the AboutYou App, Sign in with Apple works without any issues on iOS 13.6

**Comment by HenriBeck** [comment]
I'm closing this until we get more information (logs/reproducible examples).

**Comment by rknell** [comment]
Having the same issue. Did anyone here ever find the solution?
