### ISSUE TITLE
com.apple.AuthenticationServices.AuthorizationError error 1000.

### ISSUE THREAD

**Issue by MRSEREY** [aboutyou/dart_packages#137]

**Comment by MRSEREY** [comment]
- tested on simulator Iphone 11 version 13.3

**Comment by dwikresno** [comment]
i also got similar issue, 3 days ago i've tried on simulator Iphone 11 and work fine, but today, i get this error

**Comment by dwikresno** [comment]
@MRSEREY i found it, the problem is on your apple id setting, u must complete your apple id setting on simulator

**Comment by MRSEREY** [comment]
@dwikresno I already signed in my apple id into my simulator but I still got that issue

**Comment by dwikresno** [comment]
can u open setting -> password & security-> Apps using Apple ID,
can u see your apps in there, if your app appear, just trying to login again

**Comment by MRSEREY** [comment]
@dwikresno thanks, It is working now. However my app appears in Apps Using Apple ID unless I tired to login with my real device. Anyways, thanks for your help

**Comment by tp** [comment]
Glad you figured it out 👍 

Another thing to note is that you have to have an account with 2FA, so it can't be setup entirely in the simulator (as I recall), but you have to use a physical phone to set it up initially (maybe Mac would also do, haven't tried that).
