### ISSUE TITLE
[sign_in_with_apple] empty email/identifier when signing in on a device

### ISSUE THREAD

**Issue by kaarens93** [aboutyou/dart_packages#138]
Hi, when I sign in using an actual device, an account gets created without an identifier. My device is on 13.6. I don't have any issues on the simulator. Simulator works as intended and is also on 13.6. Any idea what the problem is? 

![image](https://user-images.githubusercontent.com/43043866/91107952-70e10a00-e62b-11ea-9451-f045561c0621.png)

**Comment by HenriBeck** [comment]
@kaarens93 Looks like you are using firebase, is this correct?

This looks like a similar issue as #122

**Comment by HenriBeck** [comment]
Just be aware that you only get the email and name of the user upon the first login and not on subsequent ones.

**Comment by kaarens93** [comment]
Ah I see. Yes, I'm using firebase.
Why is email/name only given on the first login and not subsequent ones? This makes it a little difficult because I'm using the email as an identifier. To fix this issue, I will use userIdentifier instead.

**Comment by HenriBeck** [comment]
@kaarens93 This is a limitation on Apples side and sadly not our own.

**Comment by kaarens93** [comment]
Good to know. Thank you for the quick response and I'll close this issue since I know what the problem is now!
