### ISSUE TITLE
[sign_in_with_apple] com.apple.AuthenticationServices.AuthorizationError error 1000

### ISSUE THREAD

**Issue by echoneet** [aboutyou/dart_packages#141]
I have this issue on lib version 2.5.2
issue only occurs on real device, no problem on simulator.
my real device is IPhone8 on iOS 13.6.1

already tried
* check 'Sign in with apple' in capabilities (debug/release/profile).it is already enabled.
* change apple id. (both id not working)
* run as release.
* run example app.
* redownload provisioning profile

btw app appears in `apple id > apps using apple id` so it success but some how error after?
i attach error i got when i run example app in debug mode and capabilities page.

<img width="1245" alt="Screen Shot 2563-09-04 at 13 08 12" src="https://user-images.githubusercontent.com/16792493/92205768-8d453800-eeb0-11ea-8fce-295a7a884652.png">
<img width="1410" alt="Screen Shot 2563-09-04 at 13 08 39" src="https://user-images.githubusercontent.com/16792493/92205786-9209ec00-eeb0-11ea-9dd7-814efa5396e1.png">

**Comment by HenriBeck** [comment]
@echoneet did you have into the logs which you see when running your app from XCode, those usually have more information.

Also, did you check if you created the Service ID in the Apple Developer Console according to https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#create-a-service-id

**Comment by echoneet** [comment]
okay i found my problem after 2 day tried. i'm really stupid lol.
when use sign in with apple in real device with touch id, just scan finger not push the button.
i need to be familiar with iOS device more. XD

however, thank you so much for response and great plugins~!
