### ISSUE TITLE
When sign in with Apple, It return correct email, but name is null.

### ISSUE THREAD

**Issue by joumduk** [aboutyou/dart_packages#145]
I request both scope name and email like this

`final appCredential = await SignInWithApple.getAppleIDCredential(
          scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
          ],
          webAuthenticationOptions: WebAuthenticationOptions(
            clientId: 'my customer id'
            redirectUri: Uri.parse(
              'https://bangkok-metro-trip.firebaseapp.com/__/auth/handler',
            ),
          ),
        );`

It return correct email address but name is null.

how can I solve this problem?

**Comment by tr-stan** [comment]
it's supposed to provide a null value at that point. you don't get the private email relay address until after you've used POST on the `signInWithAppleEndpoint` -- in the example code you get:
`final session = await http.Client().post(
        signInWithAppleEndpoint,
      );`
then the `session` response should contain the relay email address

**Comment by HenriBeck** [comment]
@joumduk we will need a bit more info here:

- Operation System
- Operation System Version
- Library Version

Just FYI: The `redirectUri` will not work for web based authentication flows, for this please follow our steps in the [readme](https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#server)

**Comment by joumduk** [comment]
Mostly used this library for login ios part
When developing, used Mac OS with VS Code 

I Used this library  
  - sign_in_with_apple: ^2.5.2

This is my flutter doctor result


[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale ko)
    • Flutter version 1.20.4 
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/gimgwangmin/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1


Previously, the library is worked correct
In time, I can get email and name both

But now, it is not return name information from server

**Comment by joumduk** [comment]
I found a the case of not return name.

When i login by face detector of apple, It return name data.
but when i login by fingerprint, it not return name data

**Comment by vadrian89** [comment]
Hello, 
I also faced this issue, but only after the first usage.
The first time when I add the app to the list of apps using sign with Apple ID it returns the full name, afterwards it returns null.

Thanks @HenriBeck for the work on the package.

**Comment by HenriBeck** [comment]
@vadrian89 you only get the name and email on the first login, on subsequent logins these fields will be `null` (also across devices), so you will need to save this data on your server

**Comment by vadrian89** [comment]
> @vadrian89 you only get the name and email on the first login, on subsequent logins these fields will be `null` (also across devices), so you will need to save this data on your server

Oh, so that's how it works :D, thought maybe it was related to his problem and might have helped. 
Yeah, on first login I add the name in my database for future usage. 
Best regards!

**Comment by HenriBeck** [comment]
As this issue has been resolved, I will close this for now.

**Comment by giacomok** [comment]
I am sorry to answer to a closed issue, but I did first login in my app and I didn't save user credentials. Now I do not know howto delete app info on the iphone to do again a first login.

**Comment by tr-stan** [comment]
you go to settings -> icloud settings -> password & security -> apps using apple id -> your app and then select 'Stop Using Apple ID'. Then you might want to run a flutter clean & flutter pub get again before running the app.

**Comment by MattyBoy4444** [comment]
I have the same problem.  If I remove the app from my account and then relogin, I get the email address but the name is ALWAYS null.  Has anyone figured out how to get around this?

**Comment by HenriBeck** [comment]
@MattyBoy4444 as there have been a few issues mixed up in this specific one, could you please create a new one with exact steps that you did?

Please keep in mind that you only get the email and name on the first sign up and not on subsequent sign-ins.
