### ISSUE TITLE
Is serviceID must be different than the bundleID?

### ISSUE THREAD

**Issue by SeasonLeee** [aboutyou/dart_packages#146]
I tried to create a serviceID with the exact same identifier as bundleId, and failed.

for example, my bundleId is `com.example.app.`

and I used it in serviceId also `com.example.app`

And it just failed...

What should I do then?

Does this package has to have a serviceId? 

In my understanding, serviceId is for sign in with apple on platform like website, but ours should be an APP right?

Did I misunderstand something?

Thanks!

**Comment by HenriBeck** [comment]
@SeasonLeee yes, the bundle id and service id need to be different. For our app, we should use `${bundleId}.service` as the service id.

You will only need the service id when you also want to provide Sign in with Apple support on Android; for iOS, you just need to create the service.

**Comment by HenriBeck** [comment]
Let us know if you have further questions, closing this issue until then

**Comment by SeasonLeee** [comment]
@HenriBeck hey Henri, thanks for the response! And no, I don't have any further question for now, thanks!
