### ISSUE TITLE
Sign in with Apple hangs on iPhone Simulator

### ISSUE THREAD

**Issue by enyo** [aboutyou/dart_packages#148]
After asking me to enter my password, it just spins endlessly

![image](https://user-images.githubusercontent.com/133277/94043778-a36a5800-fdcd-11ea-8009-cf95b679c68d.png)

**Comment by HenriBeck** [comment]
Same issue as #147 

Please have a look into issue #144, at this point this isn't an issue with our library but with XCode. (See [comment](https://github.com/aboutyou/dart_packages/issues/144#issuecomment-696157418))

There hasn't been a fix discovered yet sadly
