### ISSUE TITLE
Create proper Flutter examples

### ISSUE THREAD

**Issue by HenriBeck** [aboutyou/dart_packages#15]
We should have proper runnable flutter apps in our `example` directory.

**Comment by tp** [comment]
@HenriBeck Also just noticed that `state_queue` is not properly set up for the latest `pub.dev`: https://pub.dev/packages/state_queue#-analysis-tab-

Seems like an easy fix for that package.

The only downside for us that I came across, is that we can't run on iOS simulator (without setting up a local developer account, which might then cause other issues again). But for the other packages it should be fine to have something that works on Android.
