### ISSUE TITLE
Android build issue.

### ISSUE THREAD

**Issue by CanbinMei** [aboutyou/dart_packages#150]
The iOS version is working fine, but the Android version stopped working after 1 day(I didn't change any code, just try to run the app again in the next day, and it stopped working).

Here is the error I am getting:
java.lang.runtimeexception: java.lang.runtimeexception: duplicate class com.google.common.util.concurrent.listenablefuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

Here is what I tried:

1) Put this line in build.gradle file.
implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
IT DID NOT WORK.

2) Put this line in build.gradle file.
implementation 'com.google.guava:guava:27.0.1-android'
IT DID NOT WORK.

3) Delete Firebase Cloud Firestore dependency from pubspec.yaml.
IT DID NOT WORK.

4) Delete all the Firebase dependency from pubspec.yaml.
IT DID NOT WORK.

FINALLY.
I can build the app after I commented out "sign_in_with_apple: ^2.5.2" in pubspec.yaml.
So I think there is a problem with this plugin.

**Comment by HenriBeck** [comment]
This is not an issue with our plugin directly, but a dependency conflict with some other Android plugin.

@CanbinMei could you please post all your dependencies?

**Comment by CanbinMei** [comment]
> This is not an issue with our plugin directly, but a dependency conflict with some other Android plugin.
> 
> @CanbinMei could you please post all your dependencies?

Hello, thank you for helping!
Here are all the dependencies I have:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  lottie: ^0.6.0
  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  email_validator: ^1.0.5
  flutter_spinkit: ^4.1.2
  google_sign_in: ^4.5.1
#  sign_in_with_apple: ^2.5.2

**Comment by HenriBeck** [comment]
@CanbinMei the conflict happens with the `google_sign_in` package, and normally the first try that you described worked as far as we know.

**Comment by CanbinMei** [comment]
> @CanbinMei the conflict happens with the `google_sign_in` package, and normally the first try that you described worked as far as we know.

Are there any way to fix the problem so I can use both?
Most people can fix the problem with this line of code: implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
But it doesn't work in this situation.

**Comment by HenriBeck** [comment]
@CanbinMei does this work: https://github.com/aboutyou/dart_packages/issues/96#issuecomment-642901789

**Comment by CanbinMei** [comment]
> @CanbinMei does this work: [#96 (comment)](https://github.com/aboutyou/dart_packages/issues/96#issuecomment-642901789)

Yes, it worked!
Thank you very much for helping!
