### ISSUE TITLE
[sign in with apple] after entering the user info on web browser, it doesn't navigate back to the app and log 404

### ISSUE THREAD

**Issue by SeasonLeee** [aboutyou/dart_packages#151]
I have followed every steps on README, and our backend is customized one based on the example code on Glitch

![image](https://user-images.githubusercontent.com/13610283/94362872-ce67eb00-00f0-11eb-8b1d-22922dd93c3e.png)

Do you guys have any idea of how this thing happen and how to resolve it? Thanks!

**Comment by HenriBeck** [comment]
@SeasonLeee can you see the redirect happening on your server?

Otherwise maybe double-check the `token` which is embedded, this should be the body of the request encoded as `URLSearchParams`.

**Comment by SeasonLeee** [comment]
@HenriBeck Hey, thanks for responding!

But as to the question of 'seeing the redirect happening on the server', I'm afraid I can't answer that because in our project, I'm only in charge of the frontend part, in this case, the flutter implementation of the feature, sign in with apple.

So, there's no way to tell if the backend server saw the redirect was happening or not, but I did ask them, they told they don't understand the concept of 'seeing the redirect happening'........... hahaha🤣

Anyway... they are working on it... I will keep you update, thanks!

**Comment by HenriBeck** [comment]
@SeasonLeee I mean, if you can detect that the redirect to your server is appropriately happening and correctly setting the status code to `307` on your server.

You should have some logs that verify the request from Apple to your server is being processed by your server and correctly forwarded.

If this checks out, then I would have a look at what is being written into the redirect (the `token` variable I mentioned earlier) to verify the link is being built correctly.

**Comment by SeasonLeee** [comment]
@HenriBeck hey, man, you are so awesome for this detailed explanation, but I wonder if this normal?

this output is from the example app from the GitHub and the Glitch:

![image](https://user-images.githubusercontent.com/13610283/94415207-dcc90c00-01af-11eb-8cfd-db68534f8323.png)

And this is the code from example app's main.dart file:

![image](https://user-images.githubusercontent.com/13610283/94415378-0c781400-01b0-11eb-8afe-14f75bfefb0c.png)

Anything wrong about this?

**Comment by SeasonLeee** [comment]
....our backend guy misunderstood so many things... now we finally make the whole thing work... so.... I'm closing this issue now... I feel so embarrassing for wasting @HenriBeck your time...

Sorry... And thanks for the awesome package.
