### ISSUE TITLE
[sign in with apple]example not working (probably glitch server example)

### ISSUE THREAD

**Issue by SeasonLeee** [aboutyou/dart_packages#153]
On the flutter app, I have followed every steps in the code and in the README.

I test the example first on Android.

It successfully opened a new chrome tab and navigated to apple's site, after filled in the information and process, the tab successfully close and navigated back to the app.

But on the console, it appears that the print of the credential is `AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null)`

the screenshot:
![image](https://user-images.githubusercontent.com/13610283/94428835-ff652000-01c3-11eb-865c-08e580e23eb6.png)

while after a quite a long time, the print of the session's body is an error html page:

show in the screenshot:
![image](https://user-images.githubusercontent.com/13610283/94428906-160b7700-01c4-11eb-9295-59cd29120fa1.png)

In the meantime, the console of Glitch shows:
![image](https://user-images.githubusercontent.com/13610283/94428971-30455500-01c4-11eb-8438-b8cdf0164692.png)

My guess is due to the fact that credential is this `AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null)`, which cause error in the next flow.

Any suggestions? Please.... 

Thanks for reading...

**Comment by HenriBeck** [comment]
@SeasonLeee you are calling the `/sign_in_with_apple` endpoint on the example server, correct? So the redirect is working properly back to the app?

I'm guessing you are missing the required env variables to call the second endpoint.

**Comment by songyiYu** [comment]
Same issue 😭

**Comment by HenriBeck** [comment]
@songyiYu could you please post your log as well?

**Comment by songyiYu** [comment]
@HenriBeck No error logs found. I can see only this console log.
`console.log(Redirecting to ${redirect});`

Result
```
Redirecting to intent://callback?code=c4940acb63b06...
...
...
#Intent;package=com.pallo.passiontimerscoped;scheme=signinwithapple;end
```
I'm calling only `/callbacks/sign_in_with_apple` endpoint from dart code. 
Is there any part for me to call `/sign_in_with_apple` endpoint?

**Comment by HenriBeck** [comment]
Why are you calling the `/callbacks/sign_in_with_apple` from your dart code though? That endpoint is only used for redirecting back to apple and then back into the app and should not be called directly.

**Comment by songyiYu** [comment]
@HenriBeck I meant `WebAuthenticationOptions.redirectUri`.
```
    final appleIdCredential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
      webAuthenticationOptions: WebAuthenticationOptions(
          clientId: 'com.pallo.yeolpumta',
          redirectUri: Uri.parse(
              'https://yeolpumta-ko.glitch.me/callbacks/sign_in_with_apple'))
    );
```
Is there something wrong with this code too?

**Comment by HenriBeck** [comment]
Not directly, but there still might be something wrong with some configuration

**Comment by SeasonLeee** [comment]
Hey, people, getting the notifications during the holiday, but still, I'm going to chime in with my own experience on the subject.

So, as @songyiYu was saying, I also filled all the required `env` variables in the glitch, but, no, when the redirect happening,  there are always errors on the either the browser tab in Android platform or the console of XCode when it's on iOS platform.

![image](https://user-images.githubusercontent.com/13610283/95072632-14026480-073e-11eb-8a71-ddce08b81314.png)

but when I on the `key_contents` field, it hit me that we might filled it with the wrong content or format.

Could you provide an example? Thanks! @HenriBeck

**Comment by HenriBeck** [comment]
@SeasonLeee why didn't you change the android package identifier?

**Comment by songyiYu** [comment]
I found that string format is different between value from nodejs server and value to be parsed in the dart code.
I can see the log `intent://code=....&id_token=...;scheme=signinwithapple;end` in the glitch console. 
`id_token` might be jwt token from Apple.
but in flutter `authorization_credential.dart` line 172,
```dart
  final user = deeplink.queryParameters.containsKey('user')
      ? json.decode(deeplink.queryParameters['user']) as Map<String, dynamic>
      : null;
```
It checks if there is 'user' key in the `deeplink`. Otherwise, it returns null.
But deep link contains `id_token` in the form of jwt token.
So, I sent it from server in a format that is suitable for parsing in the dart code and it worked.

@HenriBeck I wonder why userIdentifier must be fixed `null` in android?
```dart
 return AuthorizationCredentialAppleID(
    authorizationCode: deeplink.queryParameters['code'],
    email: user != null ? user['email'] as String : null,
    givenName: name != null ? name['firstName'] as String : null,
    familyName: name != null ? name['lastName'] as String : null,
    userIdentifier: null,
    identityToken: deeplink.queryParameters['id_token'],
    state: deeplink.queryParameters['state'],
  );
```
The only thing I need is `userIdentifier`😭 so I fixed `null` to userIdentifier from server.
Is there any problem? Please let me know. Thanks!

**Comment by songyiYu** [comment]
I found that string format is different between value from nodejs server and value to be parsed in the dart code.
I can see the log `intent://code=....&id_token=...;scheme=signinwithapple;end` in the glitch console. 
`id_token` might be jwt token from Apple.
but in flutter `authorization_credential.dart` line 172,
```dart
  final user = deeplink.queryParameters.containsKey('user')
      ? json.decode(deeplink.queryParameters['user']) as Map<String, dynamic>
      : null;
```
It checks if there is 'user' key in the `deeplink`. Otherwise, it returns null.
But deep link contains `id_token` in the form of jwt token.
So, I sent it from server in a format that is suitable for parsing in the dart code and it worked.

@HenriBeck I wonder why userIdentifier must be fixed `null` in android?
```dart
 return AuthorizationCredentialAppleID(
    authorizationCode: deeplink.queryParameters['code'],
    email: user != null ? user['email'] as String : null,
    givenName: name != null ? name['firstName'] as String : null,
    familyName: name != null ? name['lastName'] as String : null,
    userIdentifier: null,
    identityToken: deeplink.queryParameters['id_token'],
    state: deeplink.queryParameters['state'],
  );
```
The only thing I need is `userIdentifier`😭 so I fixed `null` to userIdentifier from server.
Is there any problem? Please let me know. Thanks!

**Comment by HenriBeck** [comment]
@songyiYu but we already expose the `id_token` in the credential, and as far as I remember it we never get the `userIdentifier ` on the web platforms.

**Comment by songyiYu** [comment]
@HenriBeck I checked userIdentifier is not null and the value is valid.
If userIdentifier value is null, I wonder what is the parameter I can identify user?

**Comment by HenriBeck** [comment]
@songyiYu maybe the user identifier is also provided on the Web platforms. I wasn't sure anymore as it's been a few months since I last checked this.

I will be closing this issue now, if there are other questions/problems please open a new ticket.

**Comment by HenriBeck** [comment]
Also be aware that the `idToken` is a JWT where you can extract the user data as well: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple

**Comment by hao-view** [comment]
@HenriBeck Hi, i try sign in apple in android platform device, but i realised that issue same with SeasonLeee result,  AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null). Can i know why it cannot return idToken, is it the chrome issue ?

**Comment by zhukeev** [comment]
> @HenriBeck Hi, i try sign in apple in android platform device, but i realised that issue same with SeasonLeee result, AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null). Can i know why it cannot return idToken, is it the chrome issue ?

Have you fixed ? I have the same here

**Comment by hao-view** [comment]
> > @HenriBeck Hi, i try sign in apple in android platform device, but i realised that issue same with SeasonLeee result, AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null). Can i know why it cannot return idToken, is it the chrome issue ?
> 
> Have you fixed ? I have the same here

Not yet , i try online research , but can't find any solution to fix it.

**Comment by appsbykoketso** [comment]
Hi,

Experiencing the same people. What supposed to be the value for android package identifier?

**Comment by appsbykoketso** [comment]
> > @HenriBeck Hi, i try sign in apple in android platform device, but i realised that issue same with SeasonLeee result, AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null). Can i know why it cannot return idToken, is it the chrome issue ?
> 
> Have you fixed ? I have the same here

**Comment by jackwill99** [comment]
> > > @HenriBeck Hi, i try sign in apple in android platform device, but i realised that issue same with SeasonLeee result, AuthorizationAppleID(null, null, null, null, authorizationCode set? true, null). Can i know why it cannot return idToken, is it the chrome issue ?
> > 
> > 
> > Have you fixed ? I have the same here

I also have the same issue here
