### ISSUE TITLE
get email for linkWithCredential

### ISSUE THREAD

**Issue by MeshkaniMohammad** [aboutyou/dart_packages#157]
I'm following [this](https://firebase.flutter.dev/docs/auth/social/#apple) URL and i need to link `Firebase user` with `linkWithCredntial` method and because i have `facebook` and `google sign in`, i should use this method.
if I'm right, what's the way of doing this? because i think i should have `email` from apple id to get sign in methods.

**Comment by HenriBeck** [comment]
@MeshkaniMohammad I don't see how you need the email in that specific example. However, you only get the email upon the first sign up with apple, and not on subsequent logins.

**Comment by tp** [comment]
Hey @MeshkaniMohammad,

as elaborated in chat, you can access the user's email address the first time they log in with Apple, using `nativeAppleCred.email` (if you following the linked snippet).

Also as said, that might not be sufficient to merge/connect other accounts from the same user, as by default Apple with give you only a "relayed" email address, and not the user's original one. But for the cases where you know that a specific e-mail address is already registered (either directly or indirectly through a social login), you can try to connect them on Firebase.

(I don't know if Firebase also could do this out of the box. It seems like a very useful/desirable feature when working with "trusted" email addresses, but maybe there is a time component to social logins which would make this insecure. If you find anything about this in the Firebase docs, feel free to share.)

For now I would close this ticket, as it seems technically very much possible to do what you want today (and we do exactly this "linking" of credentials on perfect e-mail matches in the app that spawned this plugin).
