### ISSUE TITLE
hangs on getAppleIDCredential

### ISSUE THREAD

**Issue by niceguy1** [aboutyou/dart_packages#163]
Hi, i've tried both the example app and my app and both hanged once i click the SignInWithApple.getAppleIDCredential

once clicked:
- the spinner is rotating infinitly
- the "Continue" button greyed and than back to blue but nothing happenes
- no errors or exceptions

- flutter doctor shows no issues and app runs fine without the plugin
- few months ago everything worked and i even published my app (old versions still work)
- i didnt change anything in my code regarding this plugin

did notice that i on the apple page i could't add the Url in https://example.com/callbacks/sign_in_with_apple for some reason it's auto removed once clicked outside the box

thank you for your support !

![post](https://user-images.githubusercontent.com/22826918/97872340-8c008200-1d1e-11eb-9c8c-217f715d7cd5.png)

**Comment by sanjaymajoka** [comment]
Facing Same issue Stuck on circular indicator, Documentation for Sign In setup is not clear. (Mostly Server Setup part). 
I am facing this issue in simulator. 
Is simulator works for Apple Sign In?

**Comment by HenriBeck** [comment]
@niceguy1 @sanjaymajoka there is an issue with the iOS simulator and iOS 14/XCode 12. See #144 for more information

**Comment by HenriBeck** [comment]
Also @sanjaymajoka, a server is not directly needed for Sign in with Apple to work on iOS
