### ISSUE TITLE
AppleSignIn with Auth0 provider

### ISSUE THREAD

**Issue by mkolbusz** [aboutyou/dart_packages#166]
Is there possible to use returned credentials to login using Auth0 provder (http://auth0.com)
I have a flutter app and use this package to implement Apple Sign In feature.
I get the authorization data from the Apple like below:
```
userIdentifier = "0XXXX7.6bb65XXXXXXXXXXXXXXXX36.1XXX2"
givenName = "test"
familyName = "signing"
email = "testemail@company.com"
authorizationCode = "c372xxxxxxxa526eexxxxxx1111e.0.rwsex.SwXxxXXXdDj_XxxXXXxxX"
identityToken = "eyJraXxxuxjxxxXxxxXx.eyJXxxxxtXxxxxxxhlYXxxXXxXxXXXXX"
state = null
```
The I have tried to send the `authorizationCode` as described here in Step 3: https://auth0.com/docs/connections/nativesocial/apple
And I get the 403 Forbidded {"error":"invalid_grant","error_description":"Invalid authorization code"}

I have configured the settings in the Auth0 dashobard in Social and Applications section.
Is there any way to use the `autorizationCode` to login using Auth0?

**Comment by HenriBeck** [comment]
Sorry for the late reply here @mkolbusz. Our library only forwards you the authorization code which we receive from Apple, so there should be nothing preventing you from using Auth0.

Please double check your configuration on Auth0 side as this is outside of our library scope.
