### ISSUE TITLE
Any recommended server solutions besides Glitch?

### ISSUE THREAD

**Issue by giorgio79** [aboutyou/dart_packages#167]
I found this here on Github 
https://github.com/ananay/apple-auth-example

This one seems incomplete as it mentions:
https://github.com/ananay/apple-auth
" Important note: Apple will only provide you with the name and email ONCE which is when the user taps "Sign in with Apple" on your app the first time. Keep in mind that you have to store this in your database at this time! For every login after that, Apple will provide you with a unique ID that you can use to lookup the username in your database."

The Glitch example did not have a db either if I have seen correctly.

**Comment by tp** [comment]
@giorgio79 Our assumption is, that any system that has accounts just has their own backend including database.

So the Glitch server is just an example, but for production use you would store the token received on the user entry (to re-validate with Apple later etc.).

What's your use-case for using Sign in with Apple but not having server-side accounts?

It's basically a requirement not just from this plugin, but of how the whole system works, and how later communication between "your app" and Apple can only be happening from your "trusted" backend (as it has to have the keys from Apple).

**Comment by giorgio79** [comment]
Thanks! I am using Firebase, and I realised it is very easy with the examples posted at flutterfire.dev

**Comment by tp** [comment]
Great to hear that that works for you now: https://firebase.flutter.dev/docs/auth/social#apple

Though it seems Android is not solved from Firebase's side, but also not something this plugin can affect.
