### ISSUE TITLE
Biometric doesn't work when using apple sign in in 2 apps.

### ISSUE THREAD

**Issue by nghiashiyi** [aboutyou/dart_packages#169]
I have two apps with different Bundle ID ( same develop account ), and have already setup to those own keys, services. But when installing/running two apps on device, only the last one installed works when trying to sign in apple, another one is freeze at the screen showing FaceID (photo below).

![Group 2](https://user-images.githubusercontent.com/52031665/101126354-e5194980-362d-11eb-9605-8b6f35075306.png)

Are there any other configs that I missed? 
Thanks.

**Comment by HenriBeck** [comment]
@nghiashiyi could you maybe connect the iphone to your local mac and run your App via XCode. You should see some error message then when trying to login.

**Comment by nghiashiyi** [comment]
Unfortunately, I didn't get any lights in console, Face ID was not related to the app so there is no logs there. But anyway, I found the reason and fixing it. Thanks.
