### ISSUE TITLE
Email not getting passed

### ISSUE THREAD

**Issue by quseappdeveloper** [aboutyou/dart_packages#170]
In the scope email is added but not able to retrieve the email. Below is the code.
 SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
    ).then((credential) {
      UserRegister userRegister = new UserRegister(
        email: credential.email,
        name: credential.givenName
      );

**Comment by HenriBeck** [comment]
@quseappdeveloper you only get the email in the first login, after that it will always be null.

On the first login you will need to save the users email on your server if you want to retrieve it at a later point.

**Comment by quseappdeveloper** [comment]
Got it. That worked. We changed our design.
