### ISSUE TITLE
[sign_in_with_apple] Cannot seem to be able to get the user name

### ISSUE THREAD

**Issue by olivierbrand** [aboutyou/dart_packages#172]
I have followed the example in firestore and cannot get the real email nor the user name info after login in.

Below is the slightly modified (try/catch and return type) I got from the Firestore doc:

    Future<AuthStatus> signInWithApple() async {
    final rawNonce = generateNonce();
    final nonce = sha256ofString(rawNonce);

    try {
      // Request credential for the currently signed in Apple account.
      final appleCredential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        nonce: nonce,
      );

      // Create an `OAuthCredential` from the credential returned by Apple.
      final oauthCredential = OAuthProvider("apple.com").credential(
        idToken: appleCredential.identityToken,
        rawNonce: rawNonce,
      );

      // Sign in the user with Firebase. If the nonce we generated earlier does
      // not match the nonce in `appleCredential.identityToken`, sign in will fail.
      final UserCredential authResult =
          await FirebaseAuth.instance.signInWithCredential(oauthCredential);

      final User user = authResult.user;

      assert(!user.isAnonymous);
      assert(await user.getIdToken() != null);

      final User currentUser = _auth.currentUser;
      assert(user.uid == currentUser.uid);

      return _updateUserWithAuthenticatedUser(authUser: currentUser);
    } on SignInWithAppleException {
      return AuthStatus.unauthenticated;
    }
   }

**Comment by olivierbrand** [comment]
So it seems that I was not getting the email because I had logged in once with the proxy email option selected. So I deleted the account from firebase auth, removed the app auth from settings, and now I can get the email. HOWEVER, I cannot get the full name at all

**Comment by tp** [comment]
> So I deleted the account from firebase auth, removed the app auth from settings, and now I can get the email. HOWEVER, I cannot get the full name at all.

To my knowledge it should come out _once more_ when you remove the app from the iCloud/Security settings and then get the full form to re-fill (picking a mail and name).

But I didn't recheck with the last few iOS versions, so there might be differences now.

What we do in production is to ask for the name for the process steps where it's needed.

**Comment by Aadiyaara** [comment]
In my case I have noticed that the name field in User object property `displayName` and in providerData are both null, but whether the user is signing in for the first time or not or whether have they chosen to share their email or not, in all cases you can access the name of the user from the credential object as follows.

`
        final appleIdCredential = await SignInWithApple.getAppleIDCredential(
          scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
          ],
        );
        String fullName =
            appleIdCredential.givenName + ' ' + appleIdCredential.familyName;
`
