### ISSUE TITLE
[sign_in_with_apple] Build problem

### ISSUE THREAD

**Issue by cliffordh** [aboutyou/dart_packages#173]
I've done endless flutter cleans, pub gets, etc. but getting this error in SignInWithApplePlugin.h:

Flutter/Flutter.h file not found
Could not build Objective-C module 'sign_in_with_apple'

**Comment by tp** [comment]
@cliffordh 

Can you give some more information? What versions are you using (Flutter, Xcode, this plugin).
And does you Flutter project use the Swift or Obj-C iOS integration?

**Comment by cliffordh** [comment]
@tp I was able to solve this by deleting my iOS/Flutter/Flutter.podspec doing a clean and get. I believe the problem stemmed from switching over to flutter channel master and back to stable. But the problem appears to be resolved now.

Thanks

**Comment by BlackStriker99** [comment]
I am getting the same error. I have not switch the branch I am on the stable branch. I have tried the solution which is given by @tp  but it is not working for me.

![Screenshot 2021-02-24 at 8 51 04 PM](https://user-images.githubusercontent.com/40071991/109025996-4446a180-76e5-11eb-93a6-b79be5925b4f.png)
