### ISSUE TITLE
in android, app name is not showing here

### ISSUE THREAD

**Issue by neha-madhini** [aboutyou/dart_packages#175]
![Screenshot_1610436954](https://user-images.githubusercontent.com/40025677/104284904-d0f02400-54d8-11eb-8b95-bc92fee2ef20.png)

Also, with app name, instead of apple icon, if we want to change to app icon, how to do.

**Comment by HenriBeck** [comment]
@neha-madhini this is nothing that is in your control or ours. This is Apple's site `apple.com` which you can't modify.

**Comment by HenriBeck** [comment]
Note that the screenshotted page is also where you sign in to Apple itself, not the OAuth Flow used for the actual Sign in with Apple.

**Comment by tp** [comment]
@neha-madhini 

Usually the name and icon is set from your app. For the icon to work you might need to have at least 1 version published on the store (else I can't imagine how they get the image).

For what it's worth: We also saw some flaky Sign in with Apple issues this morning / around the time you reported the bug.

So maybe there was a bigger issue underlying it, but I can't say for sure as https://www.apple.com/support/systemstatus/ doesn't indicated anything (and offers no history of past events).
