### ISSUE TITLE
Cant see the login page on Iphone

### ISSUE THREAD

**Issue by Cedriccool** [aboutyou/dart_packages#181]
hi, and thanks first for the package.

Im using it, and it works good on android.

On iphone, I need to compile only with Codemagic.
Compilation is fine, it is pushed on Apple servers and I get the app on Testflight, but impossible to make it works, the login page is never called.

As I understand, I need to ad the "Sign in with Apple" capability.
But without XCode, i cant figure how to do that!!

Is it possible to edit the info.plist, or another file, to add this capability?

Thanks by advance!

**Comment by HenriBeck** [comment]
@Cedriccool, if you are not using XCode, we can't help you; you would have to ask Codemagic how to enable the capabilities.
