### ISSUE TITLE
[sign_in_with_apple] Backend callback question

### ISSUE THREAD

**Issue by demos77** [aboutyou/dart_packages#184]
Hi,

i have all parameters, but i don't understand why i need to code in my backend php (symfony) for the callback ...
I'm locked on this screen on the IOS emulator (the loader never finish to turn). 
Is it because i don't have code the backend callback ? 
If yes what i need to code ??

I use this code (i have try with and without lines commented). But never i call the print()

```
final credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
      // webAuthenticationOptions: WebAuthenticationOptions(
      //   clientId: 'fr.serialtrip.mobile.apple.connect',
      //   redirectUri: Uri.parse('https://serialtrip.fr/api/user/apple-login'),
      // ),
    );
    print(credential);
```

**Comment by demos77** [comment]
ok it's a bug with the simulator it's seem:

https://stackoverflow.com/questions/64178940/flutter-sign-in-with-apple-not-working-on-ios-simulator-infinite-loader

**Comment by HenriBeck** [comment]
For more information see #144
