### ISSUE TITLE
error com.apple.AuthenticationServices.AuthorizationError error 1001 when the user cancel the login action

### ISSUE THREAD

**Issue by fnoceda** [aboutyou/dart_packages#186]
When the user press in the cancel button in the apple login popup,  mi ide VSCODE show this error, this is in a real device, how to i need process the cancel action by the user? 

the complete error 

[SignInWithAppleAuthorizationException (SignInWithAppleAuthorizationError(AuthorizationErrorCode.canceled, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)))]

**Comment by fnoceda** [comment]
i solve this by a try catch

try{
      final credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        webAuthenticationOptions: WebAuthenticationOptions(
          clientId: 'py.francisco.noceda.casaoriental.shopporiental.sign',
          redirectUri: Uri.parse('https://orientalpy-48422.firebaseapp.com/__/auth/handler'),
        ),
      );

      print(credential);
      if( credential.givenName != null){ print('credential.givenName'); print(credential.givenName); }
      if( credential.familyName != null){ print('credential.familyName'); print(credential.familyName); }
      if( credential.email != null){ print('credential.email'); print(credential.email); }
      if( credential.identityToken != null){ print('credential.identityToken'); print(credential.identityToken); }
      if( credential.authorizationCode != null){ print('authorizationCode'); print(credential.authorizationCode); }
      if( credential.userIdentifier != null ){ print('userIdentifier'); print(credential.userIdentifier); }
    } on SignInWithAppleException catch(e){
        print(e);
    }


best.

**Comment by HenriBeck** [comment]
@fnoceda if the user canceled the operation there is nothing we as the library authors or you as the app developer could do.

The user canceled/aborted the login process, you may show some message indicating this but that's about it.
