### ISSUE TITLE
[sign_in_with_apple] Android - How to use plugin without backend callback

### ISSUE THREAD

**Issue by raphaaugustosilva** [aboutyou/dart_packages#188]
Hi, we are using this plugin, and it's awesome! We are going to use it in production, but we couldn't make it work without a backend server.

We will not need to validate the user session, we just want to get the Apple user`s information (email, first name) without validating the Apple user's session.

How can we use this plugin and close the Android Chrome tab without a backend server?

Thanks

**Comment by HenriBeck** [comment]
> How can we use this plugin and close the Android Chrome tab without a backend server?

No this isn't possible. The easiest solution is probably a simple serverless function where you don't really need to care about scaling and so on
