### ISSUE TITLE
[sign_in_with_apple] com.apple.WebKit.Networking error on ipad simulator

### ISSUE THREAD

**Issue by tijanirf** [aboutyou/dart_packages#190]
I submitted _**iphone only application**_ to appstoreconnect, then my submission was rejected because the sign in with apple feature is not working on the ipad. I'm trying to debug on ipad simulator and it stuck on this page:

<img width="416" alt="Screen Shot 2021-03-07 at 7 22 12 AM" src="https://user-images.githubusercontent.com/35812470/110225283-c66d6c00-7f16-11eb-947d-f3fe6c621899.png">

I saw this on the console `Could not signal service com.apple.WebKit.Networking: 113`. Anybody has the same problem?

**Comment by tijanirf** [comment]
Closing it since it related to #144, please check this [answer](https://github.com/aboutyou/dart_packages/issues/144#issuecomment-767581266)

Anyway, I found this exact error only once in the simulator. I'm not sure if it's related or not to this #144

**Comment by Abhishek01039** [comment]
Hello @tijanirf 

I am able to sign in with Apple on iPhone. The problem only here is with the iPad.
My app rejected because of this reason

```
We discovered one or more bugs in your app. Specifically, Sign In with Apple is not responsive. Please review the details below and complete the next steps.


Review device details:

- Device type: iPad
- OS version: iOS 15.1
```

Do you know some work around (although I have seen #144)?

**Comment by tijanirf** [comment]
Hi @Abhishek01039

I think ended up appealing and got accepted. I mentioned that I successfully tested it on real devices and asked them to avoid using an emulator when testing it.

If the appeal seems not working, just submit another version and hope the tester will test it using a real device

**Comment by Abhishek01039** [comment]
Yeah
Now in a real device, it's working fine

thank you
