### ISSUE TITLE
MissingPluginException on channel com.aboutyou.dart_packages.sign_in_with_apple

### ISSUE THREAD

**Issue by dgaedcke** [aboutyou/dart_packages#192]
Is anyone else hitting this recurrent flutter problem with plugin registrations?

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method isAvailable on channel com.aboutyou.dart_packages.sign_in_with_apple)
E/flutter (22084): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (22084): <asynchronous suspension>
E/flutter (22084): #1      SignInWithApple.isAvailable
package:sign_in_with_apple/src/sign_in_with_apple.dart:193`

Flutter 2.0.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (4 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by HenriBeck** [comment]
@dgaedcke which`sign_in_with_apple` version are you using?

**Comment by dgaedcke** [comment]
sign_in_with_apple: ^3.0.0
but I'm not hitting this problem any more .... seems it was related to the order of registering both old and new style plugs;  in retrospect, I don't think it was related to sign_in_with_apple
