### ISSUE TITLE
[sign_in_with_apple] Sign Up Not Completed - any ideas?

### ISSUE THREAD

**Issue by talmr-k** [aboutyou/dart_packages#195]
I'm using 2.5.2 and followed the pre-requisite steps of adding the apple sign in capability.

Here's the issue I am facing when running my app on my iPhone SE (2020):

![image](https://user-images.githubusercontent.com/16346366/110727454-2b9fb680-81d0-11eb-8bd6-ae667363450c.png)

The only additional information I have is this:

`Authorization failed: Error Domain=AKAuthenticationError Code=-7003 "(null)"`

I'm not able to find anything about that (seriously, try googling it too).  Any ideas?

**Comment by casualcoder404** [comment]
For me it was working before but now it is showing this exact message. i'm using sign_in_with_apple: ^3.0.0

**Comment by valvoline** [comment]
Same problem here. Used to work since today. No changes at all in the project.

**Comment by weAreCoine** [comment]
Same issue here, no way to find out any ideas for now...

**Comment by valvoline** [comment]
> Same issue here, no way to find out any ideas for now...

To me, the problem seems not related to the widget itself. Sounds like an Apple issue as depicted previously here:

https://developer.apple.com/forums/thread/122458

and here:

https://developer.apple.com/forums/thread/128443

**Comment by HenriBeck** [comment]
Hey, thanks for the report. Are there maybe more logs within XCode itself in the console?

**Comment by HenriBeck** [comment]
And can someone please verify that this also happens with the previous version of `sign_in_with_apple` (2.x.x). The 3.x.x release only contained the NNDB support so I would be very surprised if this caused the error.

**Comment by valvoline** [comment]
No log on Xcode, since the Delegate it's not called at all. I breakpointed on `SignInWithAppleAvailablePlugin.swift` and noticed that when the error above is returned no delegate is called at all. At then end, the call goes into timeout.

**Comment by HenriBeck** [comment]
@valvoline are you passing a `nonce` or `state` to the `getAppleIDCredential`?

**Comment by valvoline** [comment]
no, calling that way:

```Dart
  _loginWithApple() async {
    var credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
    );

    var credentialState = await SignInWithApple.getCredentialState(credential.userIdentifier);

    switch (credentialState) {
...
...
```

**Comment by talmr-k** [comment]
@HenriBeck I'm debugging through the bridging code and noticing that I'm getting one more error -

```
2021-03-11 11:42:06.080205-0800 Runner[7947:1867163] [core] Authorization failed: Error Domain=AKAuthenticationError Code=-7071 "(null)"
Printing description of $R52:
"The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)"
```

btw that 1000 error code - https://developer.apple.com/documentation/authenticationservices/asauthorizationerror/code/unknown  

I put a breakpoint here https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/darwin/Classes/SignInWithAppleAvailablePlugin.swift#L233

**Comment by valvoline** [comment]
This one, tipically is related to missing AppleSignIn capability. Shouldn't be related to the issue descripted above.

**Comment by talmr-k** [comment]
Ah.  Then I still have no idea and stuck :(

I have the capabilities added (removing it gives a 7026 error).

**Comment by valvoline** [comment]
Are you trying on simulator?

**Comment by talmr-k** [comment]
No, I am using physical device iphone SE (2020).

**Comment by valvoline** [comment]
But are you getting also the error `Sign Up Not Completed`, right?

**Comment by talmr-k** [comment]
Yes getting that error.

**Comment by HenriBeck** [comment]
@valvoline @talmr-k, do you know if this happens for new users, e.g., a real sign up where users didn't authenticate previously with SiwA for your App, or does this happen for a previously authenticated user?

**Comment by valvoline** [comment]
@HenriBeck This's for sure a new user. However, please note, that this's completely unrelated to server-side communication with our backend. The proble, in fact, is very early during the AppleSignIn stage. In fact, as I wrote before, we never get the delegate trigger for the completed operation.

**Comment by talmr-k** [comment]
Same here.  This is related solely to the ios apple sign in process.  Thanks!

**Comment by HenriBeck** [comment]
Let's keep this issue open until we find some more information in case other devs also run into this issue.

Did anyone already try to contact Apple support (or the Apple Developer Forums for that matter) even if they are not very helpful in most situations? Atleast I couldn't find any useful threads in the Dev Forums of the issue described here.

**Comment by valvoline** [comment]
@HenriBeck relevant thread on Apple Developer Forum:

https://developer.apple.com/forums/thread/122458

Also, yes. I opened an fb with Apple: FB9039896

**Comment by thassio-vinicius** [comment]
Any news on this? I'm using firebase as backend and getting the exact same error

**Comment by JT501** [comment]
same here, both on simulator and real devices

**Comment by thassio-vinicius** [comment]
Quick update: apparently it's working in release. Have you guys tried that?

**Comment by valvoline** [comment]
Was one of the first try. Unfortunately not working here on release. We also tried on Testflight. Nothing.

**Comment by casualcoder404** [comment]
> @valvoline are you passing a `nonce` or `state` to the `getAppleIDCredential`?

I'm passing nonce, still same issue.

**Comment by valvoline** [comment]
Quick update. Moving from Managed Xcode profile, to generated one solved the issue.

**Comment by JT501** [comment]
Update: It suddenly works on my Real Device but I did nothing. I am quite confused now :dizzy_face:. Btw, it is still not working on simulator.

**Comment by JT501** [comment]
> same here, both on simulator and real devices

Update: It suddenly works on my Real Device but I did nothing. I am quite confused now 😵. Btw, it is still not working on simulator.

**Comment by talmr-k** [comment]
Holy moly - it works for me as well.  It had never worked for me, but magically it is working.

I will certainly consider this a Friday miracle 😅 I hope it works for others also, who are facing this same exact issue.

**Comment by thassio-vinicius** [comment]
May Steve Jobs bless you all

**Comment by casualcoder404** [comment]
I guess it was something from the Apple side which they fixed. @JT501 It's again a bug of Xcode/ios14

**Comment by Hernanprograma** [comment]
I tried on ios 15.2 (simulator) ios 13.7(real device) and don't works.

On Ios 13.2 (simulator works)

**Comment by WaydataCloud** [comment]
@conor909 Same here

**Comment by Suzefa** [comment]
There is a Tip check in you apple developer account in app id make sure your server link is accurate or empty if you are not using server auth for your apple sign in. 

The issue will Resolve mine was resolve by removing the server link becasue Im not using it.

<img width="1552" alt="Screenshot 2022-12-28 at 11 17 47 AM" src="https://user-images.githubusercontent.com/92567854/209767403-c6915488-ba3e-45cb-8234-627bc170fa6e.png">

**Comment by Suzefa** [comment]
There is a Tip check in you apple developer account in app id make sure your server link is accurate or empty if you are not using server auth for your apple sign in.

The issue will Resolve mine was resolve by removing the server link becasue Im not using it.

<img width="693" alt="Screenshot 2022-12-28 at 11 25 21 AM" src="https://user-images.githubusercontent.com/92567854/209768029-649bbd40-b5af-4dff-a272-1b0585c09208.png">
