### ISSUE TITLE
unable to process request due to missing initial state.

### ISSUE THREAD

**Issue by dharmeshgondaliya** [aboutyou/dart_packages#200]
sign_in_with_apple: ^3.0.0

![Screenshot_2021-03-26-11-32-26-46](https://user-images.githubusercontent.com/71999131/112590031-2b3a2900-8e28-11eb-8f2b-b598145216d8.png)

in Android device.

**Comment by rossnguyen** [comment]
I got similar issue in Android device. The login process almost done but the last step was fail cause: unable to process request due to missing initial state.

**Comment by HenriBeck** [comment]
From the image, it almost looks like you are using firebase for the callback URL. This is not supported by this plugin and you will need to have your own custom server as described in the [README](https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple#server)
