### ISSUE TITLE
Event cancel btn IOS 

### ISSUE THREAD

**Issue by Larens94** [aboutyou/dart_packages#201]
Hi everyone, how can I hook the "cancel" event to be able to display a message to the user "login canceled"?

Sincerely
![Schermata 2021-03-28 alle 01 04 50](https://user-images.githubusercontent.com/32598073/112738264-ac490b80-8f61-11eb-9e2b-7ae44bbde062.png)

**Comment by HenriBeck** [comment]
In such a case you should get an [SignInWithAppleAuthorizationException](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/exceptions.dart#L114) thrown with the `code` of [AuthorizationErrorCode.canceled](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/exceptions.dart#L96)

**Comment by ariefwijaya** [comment]
> In such a case you should get an [SignInWithAppleAuthorizationException](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/exceptions.dart#L114) thrown with the `code` of [AuthorizationErrorCode.canceled](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/exceptions.dart#L96)

I've tried to catch it, but it was returned the wrong exception. I got 
> SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

instead of `AuthorizationErrorCode.canceled` . how to solve it?

**Comment by Ziven-n** [comment]
> instead of `AuthorizationErrorCode.canceled` . how to solve it?

```
                      try {
                        final result =
                            await SignInWithApple.getAppleIDCredential(
                          scopes: [
                            AppleIDAuthorizationScopes.email,
                            AppleIDAuthorizationScopes.fullName,
                          ],
                        );
                        debugPrint('$result');
                      } on SignInWithAppleAuthorizationException catch (e) {
                        switch (e.code) {
                          case AuthorizationErrorCode.canceled:
                            showToast('');
                            break;
                          case AuthorizationErrorCode.unknown:
                            showToast('');
                            break;
                          default:
                        }
                      }
```
