### ISSUE TITLE
Conflicting overloads

### ISSUE THREAD

**Issue by Bharavi26** [aboutyou/dart_packages#203]
pub-cache\hosted\pub.dartlang.org\sign_in_with_apple-1.1.0\android\src\main\kotlin\de\aboutyou\mobile\app\sign_in_with_apple\SignInWithApplePlugin.kt: (20, 3): Conflicting overloads: public open fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding): Unit defined in de.aboutyou.mobile.app.sign_in_with_apple.SignInWithApplePlugin, public open fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding): Unit defined in de.aboutyou.mobile.app.sign_in_with_apple.SignInWithApplePlugin

-----------------
i am receiving this error
---------------
flutter doctor

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 1.22.5 at F:\flutter_sdk\flutter
    • Framework revision 7891006299 (5 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /AppData/Local/Android/Sdk
    • ANDROID_SDK_ROOT = \AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] VS Code (version 1.55.2)
    • VS Code at \AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (1 available)
    • vivo 1818 (mobile)  • Android 11 (API 30)

Process finished with exit code 0

**Comment by HenriBeck** [comment]
@Bharavi26 what is the content of `pub-cache\hosted\pub.dartlang.org\sign_in_with_apple-1.1.0\android\src\main\kotlin\de\aboutyou\mobile\app\sign_in_with_apple\SignInWithApplePlugin.kt`?

**Comment by Bharavi26** [comment]
@HenriBeck sirn thank you for your response
 i solved that by setting  sign_in_with_apple: 2.5.4 version
