### ISSUE TITLE
Cannot log it

### ISSUE THREAD

**Issue by erperejildo** [aboutyou/dart_packages#204]
```
try {
      final credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ]
      );
      print(credential);
    } on SignInWithAppleException catch (e) {
      print(e);
    }
```

If I provide a wrong password it fails immediately and it asks again for it but if I put the right one it loads all the time without process any login:

<img width="182" alt="Screenshot 2021-05-08 at 13 02 22" src="https://user-images.githubusercontent.com/5629919/117536831-a5e88d80-affd-11eb-805d-490b8204956e.png">

I tried on the emulator, on real device doesn't compile (can't say if it's related to this)

**Comment by HenriBeck** [comment]
@erperejildo this is a known issue on an iOS 14 simulator, see #144 for more information.

On a real device it should however work when correctly configured.

**Comment by erperejildo** [comment]
I have used other apple sign in packages with same simulator but didn't have any issues like this. Any plans to fix it or the idea is move away from that version on simulators ony?
