### ISSUE TITLE
Domain AKAuthentication Error and Operation Couldn't be completed errors

### ISSUE THREAD

**Issue by grapeworksdev** [aboutyou/dart_packages#208]
Hello,

I've been running into the following errors when I try to launch on a physical iOS device (iOS 14.5):
[core] Authorization failed: Error Domain=AKAuthenticationError Code=-7026 "(null)" UserInfo={AKClientBundleID=my.package.name}

flutter: SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))

And the following error when I try launching on an iOS simulator:
SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))

I have everything set up correctly with Sign in With Apple capability.

Any idea what is happening here?

Thanks

**Comment by HenriBeck** [comment]
The `AKAuthenticationError Code=-7026` error usually means that the Sign in With Apple capability is not set up properly.

Maybe double-check that the capability is added for all targets and not just `Release` for example.

Regarding the issue in the simulator, we would need further logs from XCode for this, but please be aware that there is an issue for some users with iOS 14 and the simulator: #144

**Comment by grapeworksdev** [comment]
I was able to get it to work. Not sure what the issue was, because I had the capabilities all set up

**Comment by alessandroderoma** [comment]
Having the same issue. I added the "Sign in with Apple" capability in my apple developer account, i synchronized certificates on XCode and added the "Sign in with Apple" capability for all runners and configurations, it is showing up correctly. I cleaned the build directory and rebuilt with XCode, then I went to Android Studio and runned the flutter project on a real iPhone connected to my MacBook. When tapping on "Sign in with Apple" I'm getting `AKAuthenticationError Code=-7026`.

**Comment by akshaybhange** [comment]
> The `AKAuthenticationError Code=-7026` error usually means that the Sign in With Apple capability is not set up properly.
> 
> Maybe double-check that the capability is added for all targets and not just `Release` for example.
> 
> Regarding the issue in the simulator, we would need further logs from XCode for this, but please be aware that there is an issue for some users with iOS 14 and the simulator: #144

I'm facing same issue after creating flavors for app. Checked the capability is added for all targets. 
running it on physical device where I've already tested this (removed from settings->passwords->apps using apple sign in to login again)
Not sure what is the issue. when I run project from xcode it works but when running from flutter (AS) it doesn't work
