### ISSUE TITLE
refresh token Apple ID

### ISSUE THREAD

**Issue by jordytomara** [aboutyou/dart_packages#212]
after token expired, I dont know to get valid token again. please help example or link

**Comment by HenriBeck** [comment]
@jordytomara, you always get an `access_token` and a `refresh_token` from apple. So in case the `access_token` expires, you can call the apple server with the refresh tokens to get a new one.

https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens

However, you are also supposed to refresh your tokens once per day according to this document so you should never get expired tokens: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user

**Comment by cmedamine** [comment]
@HenriBeck please can you explain more about this, i have same issue
