### ISSUE TITLE
Do I need the Glitch server 

### ISSUE THREAD

**Issue by premtemp1** [aboutyou/dart_packages#215]
Hello,
  Can you please let me know if I need the Glitch server. I am only authenticating with iOS (no android or macos). The description is not clear. Are there any proper flutter example for this case.

can someone who got this to work only for iOS without the server please post an example code . I was using "flutter_apple_sign_in "by Tom Gilder but it has been discontinued

Thanks

**Comment by JonasKuschel** [comment]
I guess you are looking for: [the_apple_sign_in](https://pub.dev/packages/the_apple_sign_in)
As stated in the readme of the old package this is the continued package.

**Comment by tp** [comment]
@premtemp1 The Glitch server is just provided as an example of how to handle the callbacks Apple will redirect back to you after the user logged in.

There is the need of some server component to verify the tokens Apple passes to you (which needs to happen frequently, suggested renewal is once a day).

**Comment by HenriBeck** [comment]
@premtemp1, please also know that the Glitch server is only needed for the Android integration. For iOS, you only need the server component to store and verify the data you get upon the first signup, as @tp mentioned.
