### ISSUE TITLE
Request for Complete Server Example with Token Validation and Session

### ISSUE THREAD

**Issue by grapeworksdev** [aboutyou/dart_packages#216]
Hello,

I have been struggling to understand exactly what I need to do after I receive the Apple ID Credential.

I followed the documentation and am using sign_in_with_apple with Firebase Authentication.

It seems there is a lot of confusion amongst developers trying to figure this out and I haven't found any complete answers.

I am successfully able to complete the initial sign in and subsequent sign ins, but I don't know if I am doing the subsequent sign ins correctly. I am using the credentials I received in the initial Sign in With Apple flow, so I am not using any of the credentials in the call do Apple's endpoint, as shown in the documentation using the Glitch server.

A complete example would be best, but my main questions are
- Do I need to get a refresh Token from Apple's API or can I continue to use the initial credentials I received?
- How do I create a session in my system using the post request response from Apple's API?
- How do I integrate this with Firebase? Do I need to set the Firebase token using the token I receive from Apple?

My code is below. 
Appreciate any help on this.

`Future<FirebaseAuthResultStatus> signInWithApple() async {
    print('Signing in user with Apple...');

    SharedPrefs _sharedPrefs = serviceAndViewModelLocator<SharedPrefs>();

    // To prevent replay attacks with the credential returned from Apple, we
    // include a nonce in the credential request. When signing in in with
    // Firebase, the nonce in the id token returned by Apple, is expected to
    // match the sha256 hash of `rawNonce`.
    final rawNonce = generateNonce();
    final nonce = sha256ofString(rawNonce);

    try {
      // Request credential for the currently signed in Apple account.
      final appleCredential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        nonce: nonce,
        webAuthenticationOptions: WebAuthenticationOptions(
          clientId: SIGN_IN_WITH_APPLE_SERVICE_ID,
          redirectUri: Uri.parse(GLITCH_REDIRECT_URI),
        ),
      );

      print('Received Apple ID Credential: $appleCredential');
      print('Apple ID Credential First Name: ${appleCredential.givenName}');
      print('Apple ID Credential Last Name: ${appleCredential.familyName}');
      print('Apple ID Credential Email: ${appleCredential.email}');
      print('Apple ID Credential Authorization Code: ${appleCredential.authorizationCode}');
      print('Apple ID Credential User Identifier: ${appleCredential.userIdentifier}');

      // If it is the initial sign in, save the email and name data from Apple
      // Save the user data to shared prefs

        // Save the name if available
        String? firstNameApple = appleCredential.givenName;
        String? lastNameApple = appleCredential.familyName;
        if(firstNameApple != null && lastNameApple != null) {
          String appleFullName = '$firstNameApple $lastNameApple';
          print('Saving name data from Apple: $appleFullName');
          // Updated Shared Prefs
          _sharedPrefs.setAppleFullName('$appleFullName');
          // Update Firebase User
          updateUserDisplayName(updatedFullName: appleFullName);
        }

        // Save the email if available
        String? emailApple = appleCredential.email;
        if(emailApple != null) {
          print('Saving email data from Apple: $emailApple');
          // Update shared Prefs
          _sharedPrefs.setAppleSignInEmail(emailApple);
          // Update Firebase User
          updateUserEmail(updatedEmail: emailApple);
        }

      // This is the endpoint that will convert an authorization code obtained
      // via Sign in with Apple into a session in your system
      final signInWithAppleEndpoint = Uri(
        scheme: 'https',
        host: GLITCH_PROJECT_URI,
        path: '/sign_in_with_apple',
        queryParameters: <String, String>{
          'code': appleCredential.authorizationCode,
          if (appleCredential.givenName != null)
            'firstName': appleCredential.givenName!,
          if (appleCredential.familyName != null)
            'lastName': appleCredential.familyName!,
          'useBundleId':
          Platform.isIOS || Platform.isMacOS ? 'true' : 'false',
          if (appleCredential.state != null) 'state': appleCredential.state!,
        },
      );

      final session = await http.Client().post(
        signInWithAppleEndpoint,
      );

      // If we got this far, a session based on the Apple ID credential has been created in your system,
      // and you can now set this as the app's session
      print('Session created: $session');
      print('Session body: ${session.body}');

      // Create an `OAuthCredential` from the credential returned by Apple. Use the values from the first Apple Sign in
      final oauthCredential = auth.OAuthProvider("apple.com").credential(
          accessToken: appleCredential.authorizationCode,
          idToken: appleCredential.identityToken,
          rawNonce: rawNonce);

      // Sign in the user with Firebase. If the nonce we generated earlier does
      // not match the nonce in `appleCredential.identityToken`, sign in will fail.
      try {

        final userCredential =
        await _firebaseAuth.signInWithCredential(oauthCredential);

        // Get the firebase user
        final auth.User? firebaseUser = userCredential.user;

        if(firebaseUser != null) {
          _authResultStatus = FirebaseAuthResultStatus.successful;
        }

        else {
          _authResultStatus = FirebaseAuthResultStatus.undefined;
        }

      } catch(firebaseAuthException) {
        print('FIREBASE_AUTH_EXCEPTION: $firebaseAuthException');
        _authResultStatus =
            FirebaseAuthExceptionHandler.handleException(firebaseAuthException);
      }
    } catch (signInWithAppleException) {
      print('SignInWithAppleException: $signInWithAppleException');
      SignInWithAppleAuthExceptionHandler.handleException(signInWithAppleException);

    }

    return _authResultStatus;
  }`

**Comment by HenriBeck** [comment]
@grapeworksdev we can't provide a full example as this will look different for every user.

In case you are using Firebase, you should just be able to pass the result you get from our library to Firebase and Firebase will take care of validating the credentials and the refresh tokens, etc.
