### ISSUE TITLE
[sign_in_with_apple] AuthorizationAppleID get null

### ISSUE THREAD

**Issue by minxstudio** [aboutyou/dart_packages#217]
I am trying sign in apple with android flutter app. I follow docs and setup firebase, apple sign in service..

In firebase log, I got

```
 intent://callback?code=...&id_token=...#Intent;package=<android-package>;scheme=signinwithapple;end
```

But when I `print(appleCredential.toString())` it got null data like below

```
    final appleCredential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
      webAuthenticationOptions: WebAuthenticationOptions(
        // Setup at: https://developer.apple.com/account/resources/identifiers/list/serviceId
        clientId: '<my-apple-service-id>',
        redirectUri: Uri.parse(
          '<firebase-sigin-with-apple-fuction-url>'
        ),  
      )
    );
```

Result:

```
AuthorizationAppleID(null, null, null, null, null)
```

I am using version 3.0.0

```
sign_in_with_apple: ^3.0.0
```

flutter doctor information:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)
```

Can some one help me, thank you very much!

**Comment by LEECHHE** [comment]
#109 
I fixed the same issue. Try it again after revoking the account.

**Comment by HenriBeck** [comment]
@minxstudio two things here:

The `code` is still set on the result in the `authorizationCode` field.

And the rest of the data is `null` due to the restriction on Apple's side that you only get this data upon the first signup; on subsequent logins, this will always be `null`.

**Comment by Umar888** [comment]
@HenriBeck but userIdentifier should not be null. Why it is null?

**Comment by brasizza** [comment]
so  which field we can see if the user already have  logged in my app to get his user?
