### ISSUE TITLE
Pass extra data to intent://callback

### ISSUE THREAD

**Issue by rj76** [aboutyou/dart_packages#218]
Hello,

Currently I'm passing `code` and `id_token` back to the App using the `intent://callback{params}#Intent;package=com.myapp.app.myapp;scheme=signinwithapple;end` redirect and this works fine.

In my situation, Apple's response (on my backend) contains the user object (first name, last name) that I need in the App for sign up. I would like to also pass this user object back to the intent callback.

So my question is: can I add extra data to this callback that I can use in the App?

Kind regards,
Richard

**Comment by HenriBeck** [comment]
@rj76, do I understand you correctly:

You are already doing the token verification in the redirect callback and then connect to your database where you store the user's name?

**Comment by rj76** [comment]
Yes, I need some more information about the user after they are logged in, and will create that user from the app with that extra information.

**Comment by HenriBeck** [comment]
@rj76 what we do for these cases is call another endpoint from within the App once the `callback` opens our App again.  
And there, you can then pass the `code` and `id_token` to your server and do the authorization.

The benefit of that approach is that it also works for iOS and doesn't require two separate code flows in your application.

**Comment by rj76** [comment]
This is the case; so when "sign in with apple" succeeds and redirects to an endpoint on the server, the first time it contains a user JSON object. After that I do the normal user login on the backend to do the authorization:

sign in with apple -> apple -> POST to endpoint on backend with user data -> intent: app -> backend authorization -> done

It's just the thing that Apple only sends this user object once (the first time), and I can't store it in the endpoint that does the redirect to the `intent` because I don't have an email or something to identify the user with...

**Comment by HenriBeck** [comment]
@rj76, but you do get all the data available in the callback and your Flutter code, so there is no need to store anything in the `callback` endpoint.

**Comment by rj76** [comment]
As far as I understand the initial call being made is from Apple going to my backend (defined in `redirectUri` in `WebAuthenticationOptions`), and the backend is redircting back to the App as described in the issue. So I do have the user object there, but I can't store it with any user because that doesn't exist yet.

**Comment by HenriBeck** [comment]
But why do you want to store it within the `redirectUri` callback from Apple?

Just do a separate HTTP call once the user is redirected back to the App from your dart code.

Note that the `redirectUri` is also never called/invoked for the flow on iOS

**Comment by rj76** [comment]
> Note that the `redirectUri` is also never called/invoked for the flow on iOS.

This simply is not true, it's always called as described here [https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332115](url)

**Comment by HenriBeck** [comment]
> This simply is not true, it's always called as described here https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332115

Other platforms are Web and Android platforms, not iOS
