### ISSUE TITLE
Hey Guys I wanted to know if we can give an option to login in with passcode/password once the facial recognition fails?

### ISSUE THREAD

**Issue by akashgk** [aboutyou/dart_packages#224]
Hey Guys I wanted to know if we can give an option to login in with passcode/password once the facial recognition fails?

**Comment by HugHunter** [comment]
You can use this package if you want to use local authentication (passcoce / biometric) 
https://pub.dev/packages/local_auth

**Comment by HenriBeck** [comment]
@akashgk, this is already the case and also not in our control but on Apple's side. 

You can try doing a Sign in with Apple flow with a mask on, and it will prompt you about continuing with the passcode (of the phone, not the iCloud password).

**Comment by RakaAlrian** [comment]
> @akashgk, this is already the case and also not in our control but on Apple's side.
> 
> You can try doing a Sign in with Apple flow with a mask on, and it will prompt you about continuing with the passcode (of the phone, not the iCloud password).

My app cannot continue the process after user input passcode or face id in ios 15.2, but its working fine when I test it in ios 13 simulator with iCloud password. Is there any addition step for device physical authentication?
