### ISSUE TITLE
Reject app When use biometric for sign in apple ios

### ISSUE THREAD

**Issue by avinash-kanjiya** [aboutyou/dart_packages#225]
We discovered one or more bugs in your app. Specifically, when we attempted to register using Sign in with Apple, no further action occurred and the app did not create an account. Please review the details below and complete the next steps.

Steps to reproduce:

1. Launch App
2. Select profile icon
3. Select Sign in with Apple
4. Use biometric feature to verify identity
5. No further action occurs

Review device details:

- Device type: iPad
- OS version: iOS 14.7.1

**Comment by HenriBeck** [comment]
@avinash-kanjiya this is most likely a problem with your application and not our library.

**Comment by HenriBeck** [comment]
And without further information other than what Apple has sent you, we can't and won't do more.

**Comment by avinash-kanjiya** [comment]
Sign in with Apple not working when use biomatric
