### ISSUE TITLE
OS version: iOS 14.7.1 not working biometric feature 

### ISSUE THREAD

**Issue by avinash-kanjiya** [aboutyou/dart_packages#227]
SignInWithAppleButton(
  onPressed: () async {
    final credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
    );

   
  },
);

biometric feature to verify identity not working real device.

**Comment by HenriBeck** [comment]
Please attach some XCode logs by connecting your device to your laptop.
