### ISSUE TITLE
Unable to process request due to missing initial state. 

### ISSUE THREAD

**Issue by dipak1267** [aboutyou/dart_packages#229]
I am facing issue while sign up with apple from android using firebase 

here is my flutter doctor v
Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale
    en-IN)
    • Flutter version 2.5.0 at /Users/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (24 hours ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/imac/Library/Android/sdk

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Users/imac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 93.0.4577.63

**Comment by ggirotto** [comment]
Seems to be related with https://github.com/firebase/firebase-js-sdk/issues/4256

**Comment by HenriBeck** [comment]
@dipak1267 we will need further information to investigate this issue, especially regarding your setup/integration with Firebase.

However, please keep in mind that you still need a custom server for the redirect URL and can't use the one provided by Firebase.

**Comment by ggirotto** [comment]
@HenriBeck 

> However, please keep in mind that you still need a custom server for the redirect URL and can't use the one provided by Firebase.

What do you mean with the custom server? Could you please provide more details? I'm experiencing the same issue. Isn't it related with https://github.com/firebase/firebase-js-sdk/issues/4256 ?

**Comment by HenriBeck** [comment]
@ggirotto what is your url that you specify in `WebAuthenticationOptions.redirectUri`?

The custom redirect server is fully documented in our README: https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple

**Comment by ggirotto** [comment]
> @ggirotto what is your url that you specify in `WebAuthenticationOptions.redirectUri`?

Since I'm using Firebase to handle the authentication as the OP, I'm using Firebase URL:

`https://<PROJECT_ID>.firebaseapp.com/__/auth/handler`

But it fails in Android devices with the same error that the OP reported

**Comment by HenriBeck** [comment]
@ggirotto, this is not supported; you will need a custom auth handler. See our README for the full instructions on how to set up this custom handler.

**Comment by tudor07** [comment]
@HenriBeck can you explicitly add this information in the documentation? I lost a day tracking the cause of this

**Comment by DarioSiroki** [comment]
> @HenriBeck can you explicitly add this information in the documentation? I lost a day tracking the cause of this

+1...
