### ISSUE TITLE
Can't get user info

### ISSUE THREAD

**Issue by eugeen3** [aboutyou/dart_packages#230]
This is the body of a function I'm using to handle apple sign in. 
```
final credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
      webAuthenticationOptions: WebAuthenticationOptions(
        clientId: 'com.entex.imin',
        redirectUri: Uri.parse(
          'https://lush-equatorial-gooseberry.glitch.me/callbacks/sign_in_with_apple',
        ),
      ),
      nonce: 'example-nonce',
      state: 'example-state',
    );
```
`credential` fields `authorizationCode`, `identityToken` and `userIdentifier` has it values, while `email`, `familyName` and `givenName` equals to null.

**Comment by HenriBeck** [comment]
@eugeen3, you only get the `email`, `familyName`, and `givenName` on the very first sign in and not on subsequent ones.
