### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by rtviwe** [aboutyou/dart_packages#232]
Frontend:
```dart
final credential = await SignInWithApple.getAppleIDCredential(
  scopes: [
    AppleIDAuthorizationScopes.email,
    AppleIDAuthorizationScopes.fullName,
  ],
  webAuthenticationOptions: WebAuthenticationOptions(
    clientId: 'my.package.name',
    redirectUri: Uri.parse(
      'https://com.backend.com/Session/Apple/Redirect',
    ),
  ),
);
```

Backend:
```C#
[HttpPost("/Session/Apple/Redirect")]
public async Task<ActionResult> AppleRedirect()
{
    using var bodyStream = new StreamReader(Request.Body);
    var bodyText = await bodyStream.ReadToEndAsync();
    var urlEncodedBody = HttpUtility.UrlEncode(bodyText);
    return RedirectPreserveMethod($"intent://callback?{urlEncodedBody}#Intent;package=my.package.name;scheme=signinwithapple;end");
} 
```

Result:
![2021-09-17-225345_412x880_scrot](https://user-images.githubusercontent.com/23663603/133846075-c2255308-4021-4192-b536-245a3cdff41d.png)

**Comment by HenriBeck** [comment]
This can be various things but is not related to our library. It's most likely some configuration issue that you created on Apple side, so please google for the error you are seeing, and you should find a solution.

**Comment by awaisabbasaa11** [comment]
I am facing the same issue, how did you solve your issue. 
PS: Can you please tell me what is 'KEY_CONTENTS' exactly? is it the Key inside the .p8 file? if yes should i copy paste the whole thing including start and end key

**Comment by rtviwe** [comment]
> I am facing the same issue, how did you solve your issue. PS: Can you please tell me what is 'KEY_CONTENTS' exactly? is it the Key inside the .p8 file? if yes should i copy paste the whole thing including start and end key

i did not solve because "this can be various things"

**Comment by HenriBeck** [comment]
@awaisabbasaa11, the `KEY_CONTENTS` should be the `.p8` file, but in our Glitch example, you need to replace all line breaks in your key with `|` as newlines are not allowed in the `.env` files.

 Please keep in mind that this isn't needed for an initial authentication flow, e.g., even without the `KEY_CONTENTS`, you will be able to go to apple, sign in, and then be redirected into your app.

**Comment by HenriBeck** [comment]
@rtviwe, as I mentioned previously, this error most likely comes from a misconfiguration in your Apple Developer Account where the Domains and Return URLs are not correctly configured.
