### ISSUE TITLE
iOS 15

### ISSUE THREAD

**Issue by anchao-lu** [aboutyou/dart_packages#234]
Enum cases with associated values cannot be marked potentially unavailable with '@available'
<img width="716" alt="截屏2021-09-22 11 49 17" src="https://user-images.githubusercontent.com/54097292/134280636-a2463600-baf0-49e1-878b-695e6f6d3d91.png">

**Comment by HenriBeck** [comment]
Thanks, we are aware and will release a fix for it in 2 hours.

Follow #213 for more information.
