### ISSUE TITLE
[with_bloc] RFC: `onInputsChange`

### ISSUE THREAD

**Issue by tp** [aboutyou/dart_packages#24]
I just came across an idea of how to make the task updating a bloc based on parent inputs cleaner in the case where the bloc shouldn't be recreated completely, but just update itself.

The current option was basically to pass a `ValueNotifier` to the bloc, which could then do it's own subscribing and updating. This lost the declarative convenience of `WithBloc` and forced the bloc to accept some "management overhead" distracting from the core flow.

So, what about an `onInputsChange` callback, that is invoked (if present) when the inputs change, instead of recreating the bloc entirely?

I think still creating a full initially by `createBloc` is still preferable over a pattern that relies on the updater also being called for the first render (as you would then have to have some empty/"loading" state in the bloc). (This is also aligned with how we handle our `Provider` creation.)

cc @HenriBeck

**Comment by HenriBeck** [comment]
Sounds good.

Though how can the user than differentiate between recreating the bloc and only updating it? 
So assuming that some input changes might cause an update rather than a recreation, but for others, the user might desire to recreate the bloc.

Or when passing an `onInputsChange` you opt entirely out of the recreation of the bloc?

**Comment by tp** [comment]
> Or when passing an onInputsChange you opt entirely out of the recreation of the bloc?

Exactly, that was the idea.

So `createBloc` would only be called once if `onInputsChange` is provided.

I don't see a way to _only_ have one or the other, except with a pattern like the current `Provider` that creates a "not fully initialized" bloc and then updates it via some setters.

---

An alternative idea that just popped into my head would be something like `createBloc(previousBloc)`, where you could do something like:

```dart
createBloc: (previousBloc) {
  if (previousBloc != null) {
    return previousBloc..updateX(x);
  }

  return Bloc(x: x);
}
```
