### ISSUE TITLE
Requested scope values are null

### ISSUE THREAD

**Issue by aipxperts-developer** [aboutyou/dart_packages#248]
Hi i run the attached demo for Apple signin and changed the BundleID. Below is the code.

```
final credential =
    await SignInWithApple.getAppleIDCredential(
        scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
        ],
    );
print(credential);
```

But it returns null values with below log.

AuthorizationAppleID(001386.ed4685f2c6964bef9762f16b10f7425e.0625, null, null, null, null)

**Comment by Magadya** [comment]
same problem, please help )

**Comment by WilkoThomassen** [comment]
Got the same issue in version 3.2.0, also downgraded to 3.0.0, issue remains

**Comment by HenriBeck** [comment]
@WilkoThomassen is correct, this is the intended behavior, and that is why you must save such data in your Database.
