### ISSUE TITLE
[sign_in_with_apple] Cannot get fullName even at first login

### ISSUE THREAD

**Issue by gboscaro-imtech** [aboutyou/dart_packages#250]
Good morning,

I am using the sign_in_with_apple package along with firebase to login users to my app. Even at the first login attempt, when I try to login with apple, the fields "name", "surname" and "displayName" are always null. I know it is supposed to be like this when you login the other times, but at the first sign in I should be able to get this info.

Here's the little piece of code that does the login:

```
      final appleCredential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        nonce: nonce,
      );

      // Create an `OAuthCredential` from the credential returned by Apple.
      final oauthCredential = OAuthProvider("apple.com").credential(
        idToken: appleCredential.identityToken,
        rawNonce: rawNonce,
      );

      // Sign in the user with Firebase. If the nonce we generated earlier does
      // not match the nonce in `appleCredential.identityToken`, sign in will fail.
      UserCredential userCredential = await FirebaseAuth.instance.signInWithCredential(oauthCredential);
```

Any way to solve this?

**Comment by kirkcharlesniv** [comment]
@gboscaro-imtech have you been able to find a solution to this? as of now, problem still persists :/

**Comment by gboscaro-imtech** [comment]
> @gboscaro-imtech have you been able to find a solution to this? as of now, problem still persists :/
> 
> I have done the same, remove app from `Settings > Account > Password and Security > App that uses Apple IDs` and also through `https://appleid.apple.com/`, still not getting the fullName and email. It is also explicitly said in the scopes that I need email and fullName
> 
> ```
>       final credential = await SignInWithApple.getAppleIDCredential(
>         scopes: [
>           AppleIDAuthorizationScopes.email,
>           AppleIDAuthorizationScopes.fullName,
>         ],
>         webAuthenticationOptions: WebAuthenticationOptions(
>           clientId: XXXXXXXXXX,
>           redirectUri: Uri.parse('${F.baseUrl}/callbacks/sign_in_with_apple'),
>         ),
>       );
> ```

Nope, the problem is still there. At the moment I am signing up the user in my app without name and surname, but it look pretty bad. I do not know what to do but I don't think the problem is on my side so I'll need to wait for a fix I guess.

**Comment by kirkcharlesniv** [comment]
My only workaround I found is that use a real iOS device, instead of using any emulator/simulator. Maybe this could help you.

**Comment by gboscaro-imtech** [comment]
> My only workaround I found is that use a real iOS device, instead of using any emulator/simulator. Maybe this could help you.

Sadly I don't think it will help me because I actually always used my phone in debug mode on Xcode or Android Studio for develop the app. I never used an emulator to test this.

**Comment by Carmelo992** [comment]
Hello, I have the same problem. 
I'm using a real device and I tried to revoke access from https://appleid.apple.com
After removing the access only the email field is shown, instead the full name fields are not visible.

Are there any updates for this problem?

**Comment by cesarferreira** [comment]
This also happens to me, except I get email every time but never the full name, even tho the scope asks for it, not even after revoking access and making it the "first time"

**Comment by cyberpwnn** [comment]
Why is this closed, it doesnt work
