### ISSUE TITLE
How to handle a second login details to match with the previous user

### ISSUE THREAD

**Issue by nashsaint** [aboutyou/dart_packages#252]
Here's what I noticed.  On first login, the credentials object returns the name, email and the authorisationCode, this is good because it gives me user details that I need to display back.  

I implemented a logout when the app is idle for long time or when the app is closed, so a user will need to login again.  On the second login however, only the authorisationCode is returned and the value is different from the first login.  Even if I save the response from the first request in the local storage, I'd still have no way of comparing if the second login is the same person.

**Comment by tp** [comment]
This is by (Apple's) design, the name and email is only given once.

You can use the `userIdentifier` to correlate the sign in to a user in your system. This will be stable across logins.

https://github.com/aboutyou/dart_packages/blob/1f630269c9b069338abd488035694b88f24870e7/packages/sign_in_with_apple/lib/src/authorization_credential.dart#L21


Also see https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple for more information:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/52437/138056274-4da10bb3-f644-46b7-956d-858c6aabc2c4.png">
