### ISSUE TITLE
Null credential ANDROID 

### ISSUE THREAD

**Issue by Lyba97** [aboutyou/dart_packages#253]
I am trying to work with iOS and android but in android it does not return credentials anyone after first attempt it is just returning this when I do print(credential)

AuthorizationAppleID(null, null, null, null, null)

It's is a bit urgent can somebody tell me what I might be doing wrong. 

Below is my code 

                   `final credential =
                        await SignInWithApple.getAppleIDCredential(
                      scopes: [
                        AppleIDAuthorizationScopes.email,
                        AppleIDAuthorizationScopes.fullName,
                      ],
                      webAuthenticationOptions: WebAuthenticationOptions(
                        clientId: 'com.example.clicandeatsdeliveryAppleSignIn',
                        redirectUri: Uri.parse(
                          'https://past-acoustic-ocelot.glitch.me/callbacks/sign_in_with_apple',
                        ),
                      ),
                    );

                    print("credential state: ${credential.state}");
                    print('credentials $credential');

                    final signInWithAppleEndpoint = Uri(
                      scheme: 'https',
                      host: 'past-acoustic-ocelot.glitch.me',
                      path: '/sign_in_with_apple',
                      queryParameters: <String, String>{
                        'code': credential.authorizationCode,
                        if (credential.givenName != null)
                          'firstName': credential.givenName!,
                        if (credential.familyName != null)
                          'lastName': credential.familyName!,
                        'useBundleId': Platform.isIOS || Platform.isMacOS
                            ? 'true'
                            : 'false',
                        if (credential.state != null)
                          'state': credential.state!,
                      },
                    );

                    print("URI $signInWithAppleEndpoint");
                    final session = await http.Client().post(
                      signInWithAppleEndpoint,
                    ); print("Session $session");`

**Comment by Umar888** [comment]
@HenriBeck  but identityToken and authorizationCode is null every time

**Comment by Umar888** [comment]
@Lyba97 did you find any solution??

**Comment by joelsongsouzza** [comment]
I'm facing the same thing.

**Comment by yuanxintaxon** [comment]
same issue
