### ISSUE TITLE
[sign_in_with_apple] Is there a method for auto login in sign_in_with_apple?

### ISSUE THREAD

**Issue by TheLeaf-code** [aboutyou/dart_packages#264]
Trying to enable auto login once a user signs into our application initially with apple login. Is there a method in sign_in_with_apple to allow this, or do you know of a solution for this?

**Comment by tp** [comment]
> Trying to enable auto login once a user signs into our application initially with apple login.

I'm not sure I follow. A SiwA session is valid as long as it's not revoked (which you can find out by polling Apple's servers).

So the usual flow would be:

- Trigger SiwA
- Create session _in your system_ based on the Apple-provided credentials
  - Poll Apple daily to see that the session has not been revoked
- Store some access information for your system (e.g. session token / refresh token) on your client

Thus on any subsequent launches, you just use your own authentication mechanism and never show the Apple UI again (unless the user signed out…).
