### ISSUE TITLE
Android callback issue

### ISSUE THREAD

**Issue by lulumeimei** [aboutyou/dart_packages#266]
E/SignInWithApple(26638): Received Sign in with Apple callback, but 'lastAuthorizationRequestResult' function was `null`
E/SignInWithApple(26638): Received Sign in with Apple callback, but 'triggerMainActivityToHideChromeCustomTab' function was `null`

I get this in console after click login > continu on the web but didn't pop up the browser page.

**Comment by HenriBeck** [comment]
@lulumeimei I guess you already solved this issue on your own. Could you please share the solution so other people can fix it as well in case they run into it?

**Comment by lulumeimei** [comment]
@HenriBeck At first I thought I have to copy the platform specific code from packages/sign_in_with_apple/sign_in_with_apple/android/src/main/kotlin/com/aboutyou/dart_packages/sign_in_with_apple/SignInWithApplePlugin.kt

then i realize the walkthru in readme.md just need to add this code to Manifest

`
<activity
    android:name="com.aboutyou.dart_packages.sign_in_with_apple.SignInWithAppleCallback"
    android:exported="true"
>
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data android:scheme="signinwithapple" />
        <data android:path="callback" />
    </intent-filter>
</activity>`

**Comment by gronka** [comment]
Wow, I made the same mistake. I read "com.aboutyou" as "use your website details". Kind of unfortunate project naming.
