### ISSUE TITLE
Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by offline-first** [aboutyou/dart_packages#268]
This code part throws an exception if I running on flutter web

```dart
final appleCredential = await SignInWithApple.getAppleIDCredential(
      scopes: scopes,
      webAuthenticationOptions: Platform.isIOS ? null :
      WebAuthenticationOptions(
        redirectUri: kIsWeb ? Uri.base : Uri.parse('${Const.firebaseUrl}/__/auth/handler'),
        clientId: "${Const.packageName}.web-auth",
      ),
      nonce: sha256.convert(utf8.encode(nonce)).toString(),
    );
//error: Unsupported operation: Platform._operatingSystem
```

# Dependencies
firebase_core: ^1.10.1
firebase_auth: ^3.3.0
firebase_auth_web: ^3.3.0
firebase_app_check: ^0.0.4
....
sign_in_with_apple: ^3.3.0

**Comment by HenriBeck** [comment]
@offline-first the problem is `webAuthenticationOptions: Platform.isIOS ? null :` where you can't access the `Platform` enum in the web, you will need to add a check for `kIsWeb` before it.

**Comment by offline-first** [comment]
Oh, thanks @HenriBeck !
