### ISSUE TITLE
I can't get callback var credential = await SignInWithApple.getAppleIDCredential

### ISSUE THREAD

**Issue by ahmadvicky** [aboutyou/dart_packages#270]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale
    en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)

• No issues found!

var credential = await SignInWithApple.getAppleIDCredential(
      scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ],
    );
    
    what's wrong this code?

**Comment by HenriBeck** [comment]
I can't really say because there is not a lot of information provided.

Please provide logs but also on which platform you are trying to sign in, what happens etc.

**Comment by lecicdjuro** [comment]
The same here. var credential = await SignInWithApple.getAppleIDCredential(
scopes: [
AppleIDAuthorizationScopes.email,
AppleIDAuthorizationScopes.fullName,
],
);

This request doesn't return email and given name credentials. 
This happens on IphoneX, 15.1 IOS,  latest stable flutter version, latest XCode,  and with latest package sign_in_with_apple: ^3.3.0

**Comment by lecicdjuro** [comment]
@HenriBeck this is a production issue, and showstopper, can you do anything to fix this?

**Comment by tp** [comment]
@lecicdjuro To better understand this issue: Did this work for you in that same app before (with an older Flutter/Xcode/Plugin version), or did you try to add this for the first time and it doesn't work?

**Comment by BrunoJurkovic** [comment]
Hey there,

I'm also experiencing this bug. It's my first time using this package so I can't say if it worked before.

In my case, the above mentioned functions returns a identity token, but no email and name, the only time it did return it was the first login.

**Comment by HenriBeck** [comment]
@BrunoJurkovic this is normal, the email and name are only returned on the first login and you need to save this information no your servers.

**Comment by singlakaran** [comment]
@BrunoJurkovic are you testing in the above IOS version 15.0?

**Comment by BrunoJurkovic** [comment]
> @BrunoJurkovic are you testing in the above IOS version 15.0?
> 
> and which flutter version are you using?

Yes, IOS 15, latest flutter stable

**Comment by BrunoJurkovic** [comment]
> @BrunoJurkovic this is normal, the email and name are only returned on the first login and you need to save this information on your servers.

I see, is there any way to wipe the first login record?

**Comment by tp** [comment]
> is there any way to wipe the first login record?

@BrunoJurkovic Only if the user disassociates from your app in their Apple ID settings and then signs up again.

**Comment by singlakaran** [comment]
@BrunoJurkovic 
I am using flutter version 2.8.1
but still, apple login is not working for me.
I checked on IOS 14.5, 15.2, 15.1.

**Comment by jyashi** [comment]
Same problem here... I followed https://firebase.flutter.dev/docs/auth/social/ for apple sign in in ios but i never get past the await SignInWithApple.getAppleIDCredential(
    scopes: [
      AppleIDAuthorizationScopes.email,
      AppleIDAuthorizationScopes.fullName,
    ],
    nonce: nonce,
  ); line of code...

I just input my apple password in simulator and it keeps on loading forever.

**Comment by HenriBeck** [comment]
@jyashi do you have some logs from your XCode console?

**Comment by BrunoJurkovic** [comment]
> Same problem here... I followed https://firebase.flutter.dev/docs/auth/social/ for apple sign in in ios but i never get past the await SignInWithApple.getAppleIDCredential(
> 
>     scopes: [
> 
>       AppleIDAuthorizationScopes.email,
> 
>       AppleIDAuthorizationScopes.fullName,
> 
>     ],
> 
>     nonce: nonce,
> 
>   ); line of code...
> 
> 
> 
> I just input my apple password in simulator and it keeps on loading forever.
> 
> 
> 
> 

This is a known bug on the latest ios version on simulator. Try running it on your physical device or on simulator with ios 13.

**Comment by jyashi** [comment]
> > Same problem here... I followed https://firebase.flutter.dev/docs/auth/social/ for apple sign in in ios but i never get past the await SignInWithApple.getAppleIDCredential(
> > ```
> > scopes: [
> > 
> >   AppleIDAuthorizationScopes.email,
> > 
> >   AppleIDAuthorizationScopes.fullName,
> > 
> > ],
> > 
> > nonce: nonce,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ); line of code...
> > I just input my apple password in simulator and it keeps on loading forever.
> 
> This is a known bug on the latest ios version on simulator. Try running it on your physical device or on simulator with ios 13.

Yes i can confirm that this is only a problem on simulator and works fine on real device. 

Wish it is workable with simulator soon.
