### ISSUE TITLE
Site didn't respond

### ISSUE THREAD

**Issue by alpitebiztrait** [aboutyou/dart_packages#273]
https://flutter-sign-in-with-apple-example.glitch.me/sign_in_with_apple?code=c21xxxx8xxxx14e15a0exxxxf768203a6.0.xxxx.UPwNXt76OxxxxSv1q2ylg&firstName=xxx&lastName=xxxx&useBundleId=ture

How can I fix the issue please help me.

![Screenshot 2021-12-23 at 3 58 38 PM](https://user-images.githubusercontent.com/92528420/147243945-de28257c-1f1d-4a54-9e26-38f27ac68908.png)

**Comment by HenriBeck** [comment]
@alpitebiztrait, the server you are trying to reach is an example server and shouldn't be used at all other than by us (the maintainers of the code package). The server contains a configuration that is specific to our setup.

Please set up your server especially not using **glitch** and use some proper environment.
