### ISSUE TITLE
Can't find way out "SignOut" from Apple post login success

### ISSUE THREAD

**Issue by Vinayak27Mobility** [aboutyou/dart_packages#277]
Trying to find the way same like googleSignIn.signOut() the gmail plugin gives option. So waiting for this fix so we can add this to MVP. Please respond asap. Thanks.

**Comment by HenriBeck** [comment]
@Vinayak27Mobility there is no sign-out functionality from the client.

To sign out you just need to remove the session data that you have created in your system and stop requesting a new access token from your server.
