### ISSUE TITLE
Sign In With Apple: Broken animation on close

### ISSUE THREAD

**Issue by Klingefjord** [aboutyou/dart_packages#281]
https://user-images.githubusercontent.com/22666776/150560291-4bda7543-9ef6-4cc5-a5bf-206082bf26cf.MP4

To replicate:

```
class IntroScreen extends StatelessWidget {
  /// Builds the screen displayed when the app is first opened.
  const IntroScreen();

  static const String route = '/intro';

  @override
  Widget build(BuildContext context) {
    return SizedBox.expand(
      child: Container(
        color: Colors.white,
        child: Center(
          child: SignInWithAppleButton(
            onPressed: () async {
              try {
                AuthorizationCredentialAppleID credential =
                    await SignInWithApple.getAppleIDCredential(
                  scopes: <AppleIDAuthorizationScopes>[
                    AppleIDAuthorizationScopes.email,
                  ],
                );
                print(credential);
              } on Exception {}
            },
          ),
        ),
      ),
    );
  }
}
```

iOS 15.2
iPhone XR
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (5 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by kim-mini6** [comment]
I also have the same error. Any solution?

**Comment by Korpyc** [comment]
I've found that this issue related for iOS 15. On iPhone 7 with 14.6, I don't see this weird animation jump.

P.S. I have tested 2.5.3, 2.8.1 & 2.10.2 versions of Flutter SDK, on different devices.

**Comment by orenagiv** [comment]
+1

**Comment by naamapps** [comment]
Hey @aboutyou @HenriBeck @tp 
I am experiencing the same behaviour.
This is affecting the UX of the app and degrading the overall fluidity.
Is there any solution?

Please advise,
Thanks

**Comment by HenriBeck** [comment]
Closing this since our Library doesn't provide the UI for the Sign in Flow and only a button
