### ISSUE TITLE
[sign_in_with_apple] Split up full and partial Apple ID authentication result types

### ISSUE THREAD

**Issue by tp** [aboutyou/dart_packages#29]
…so we can have stricter assertions on which fields are expected.

**Comment by HenriBeck** [comment]
@tp I don't think a split up is necessary here anymore. I think it's only really about documentation and allowing the dart code to specify the requested scopes.

**Comment by HenriBeck** [comment]
Nevermind, it actually only provides the scope data upon the first sign up, but there is really no way of telling if it's the first sign up from what I can see.

I think we should just make this clear in the docs and this should be fine.
