### ISSUE TITLE
Apple login on Android couldn't get information about user

### ISSUE THREAD

**Issue by paninee** [aboutyou/dart_packages#290]
Hello, 

I'm trying to implement Apple login in my flutter app but I have a problem with getting the user's first name and last name on android. While on iOS is working as expected. When I first time trying to log in I should get first name and last name but on android, I don't receive that information, just receive the token. I tried to remove the app from appleId but did not get that information. 

While on my server-side code I got the user's information but couldn't send that via deep linking because I think I can't parse parameters from the callback and for me this library does it.

**Comment by HenriBeck** [comment]
@paninee the information should be inside the token which is a JWT one.

However, you should send the code to your backend which can then ask Apple for this information and send this information back to your App.

**Comment by kevin4dhd** [comment]
> Hola,
> 
> Estoy tratando de implementar el inicio de sesión de Apple en mi aplicación Flutter, pero tengo un problema para obtener el nombre y apellido del usuario en Android. Mientras que en iOS funciona como se esperaba. Cuando intento iniciar sesión por primera vez, debo obtener el nombre y el apellido, pero en Android, no recibo esa información, solo recibo el token. Traté de eliminar la aplicación de appleId pero no obtuve esa información.
> 
> Mientras estaba en mi código del lado del servidor, obtuve la información del usuario, pero no pude enviarla a través de un enlace profundo porque creo que no puedo analizar los parámetros de la devolución de llamada y, para mí, esta biblioteca lo hace.

did you manage to solve it?
