### ISSUE TITLE
[Suggestion] AuthorizationErrorCode improvement for "no-connection"

### ISSUE THREAD

**Issue by yamauchieduardo** [aboutyou/dart_packages#296]
First of all, nice plugin help me a lot.

Running some tests using the plugin I notice if the user lost his connection (internet) in the login process, an `AuthorizationErrorCode.unknown` is throw. Could be better if we have a better exception for this case, like `AuthorizationErrorCode.noConnection` or something else.

When an exception is throw, could useful to show to the user what happen.

Thanks for the attention.

**Comment by HenriBeck** [comment]
@yamauchieduardo we might not have the information that it failed due to a network error since this is not exposed by Apple: https://developer.apple.com/documentation/authenticationservices/asauthorizationerror
