### ISSUE TITLE
Unhandled Exception: SignInWithAppleNotSupportedException(Unsupported platform version: iOS 12.5.5)

### ISSUE THREAD

**Issue by William-cpu** [aboutyou/dart_packages#299]
Hello, 

Getting the below exception when trying to sign in from a physical device using XCode Version 13.2.1 (13C100)

Is sign in supported on iOS 12.5.5?

`Unhandled Exception: SignInWithAppleNotSupportedException(Unsupported platform version: iOS 12.5.5)
#0      MethodChannelSignInWithApple.getAppleIDCredential (package:sign_in_with_apple_platform_interface/method_channel_sign_in_with_apple.dart:86:7)
<asynchronous suspension>
#1      _AppleSignInButtonState.build.<anonymous closure> (package:example/Widgets/apple_sign_in_button.dart:19:28)
<asynchronous suspension>`

**Comment by HenriBeck** [comment]
Sign in with Apple is only supported from iOS 13 onwards.

**Comment by William-cpu** [comment]
Nice. Thank you for your response!
