### ISSUE TITLE
[sign_in_with_apple] Refine error handling for "password not available case"

### ISSUE THREAD

**Issue by tp** [aboutyou/dart_packages#30]
Currently we always treat the first error reported by `AuthKit` as expected, as it happens that when you request password + Apple ID credentials and the user doesn't have any passwords saved, you would just get a generic error (even though the system would only ever return one or the other credentials anyway…).

This leads to the situation that the first manual cancellation, wich is also only reported as a generic error (status 1000), causes the sheet to be shown a second time.

To workaround this, we could only treat errors within the first second as automatic rejections, and everything else and manual cancellations which should be respected.

Reference: https://github.com/aboutyou/dart_packages/pull/27#issuecomment-597757215

**Comment by HenriBeck** [comment]
I think we can also provide better errors as there is a mapping on the native side: https://developer.apple.com/documentation/authenticationservices/asauthorizationerror/code

**Comment by HenriBeck** [comment]
@tp After looking more at the whole error handling of the authorization, maybe it also makes sense to only support a single request per authorization on the Dart side.

My reasoning behind this: I didn't find a way of providing both Password and an Apple ID request where I wouldn't run into an error in case no password is stored.

**Comment by tp** [comment]
> My reasoning behind this: I didn't find a way of providing both Password and an Apple ID request where I wouldn't run into an error in case no password is stored.

We can definitely simplify this on the native side (to only allow requesting 1 at a time), so get more logic on the Dart side. I would still allow the consumer to request a list of authentications with a priority/order, so that the usage is very simple.

**Comment by HenriBeck** [comment]
@tp With the improved API, I think we can close this.

**Comment by tp** [comment]
@HenriBeck I still think it has 1 ugliness by throwing for a missing Keychain entry instead of returning `null`. But will verify and attempt a fix for that later. Consumers should definitely execute each login attempt in an individual try/catch.

**Comment by HenriBeck** [comment]
@tp I think throwing an error is more appropriate here, to be honest. I would consider this a success flow, and as you said, the user should wrap each call in a `try/catch`.

So I think it's easier to throw an error and not have to handle the `null` case in the success flow (even with NNDB coming up)
