### ISSUE TITLE
[sign_in_with_apple] `sign_in_with_apple-3.3.0/macos/Classes/SignInWithAppleError.swift:99:13: note: do you want to add missing cases?` when building for macOS

### ISSUE THREAD

**Issue by nilsreichardt** [aboutyou/dart_packages#305]
## Description
When building for macOS, you will get the following warning:
```
/Users/nils/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.3.0/macos/Classes/SignInWithAppleError.swift:99:13: warning: switch must be exhaustive
            switch code {
            ^
/Users/nils/.pub-cache/hosted/pub.dartlang.org/sign_in_with_apple-3.3.0/macos/Classes/SignInWithAppleError.swift:99:13: note: do you want to add missing cases?
            switch code {
            ^
```

## Steps to reproduce
```sh
flutter create test
cd test
flutter pub add sign_in_with_apple
flutter run -d macos
```

### Flutter
Flutter: `2.10.4`
sign_in_with_apple: `3.3.0`
XCode: `13.3.1`

**Comment by HenriBeck** [comment]
I added XCode 13.3.1 now to our CI, let's see if this fails

**Comment by erf** [comment]
Look's like [SignInWithAppleAvailablePlugin.swift](https://github.com/aboutyou/dart_packages/blob/a38f85e6035bf8029721e27a080ea19195c8fac1/packages/sign_in_with_apple/sign_in_with_apple/darwin/Classes/SignInWithAppleAvailablePlugin.swift#L83) is not handling the [transferred](https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidprovider/credentialstate/transferred) case of [CredentialState](https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidprovider/credentialstate).
