### ISSUE TITLE
Trying to resolve `invalid_client` error

### ISSUE THREAD

**Issue by shawnlauzon** [aboutyou/dart_packages#312]
I've been trying to resolve this `invalid_client` error for many hours and hoping someone could help me here. 

My Flutter client is very simple:
```
      appleCredential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName
        ],
        nonce: nonce,
      );
```
Then I pass `appleCredential.authorizationCode` to the server for verification. There I do this (taken from https://developer.apple.com/forums/thread/118135) which was referred to in the Glitch server example:

```
const key = `
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
`;

const options = {
    algorithm: 'ES256',
    expiresIn: '1d',
    audience: 'https://appleid.apple.com',
    subject: process.env.APPLE_CLIENT_ID, // this is my bundle ID: io.leofi.mobile
    issuer: process.env.APPLE_TEAM_ID,
    keyid: process.env.APPLE_KEY_ID,
};
const clientSecret = jwt.sign({}, key, options);

const bodyFormData = FormData()
bodyFormData.append('client_id', process.env.APPLE_CLIENT_ID)
bodyFormData.append('client_secret', clientSecret)
bodyFormData.append('code', authCodeFromClient)
bodyFormData.append('grant_type', 'authorization_code')

axios.post('https://appleid.apple.com/auth/token', {
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    data: bodyFormData
}).then(result => console.log('Response from Apple', result.body)).catch(err => console.error(err))
```

I've tried this basic flow in Postman and also get `invalid_client` error. And I've tried many variations of this, but I always get the same error. I'm wondering if I need to pass the `redirect_uri`? If so, isn't it something I need to pass in the original flutter call? And unless I'm missing it, I don't see a way of setting that unless I use a service ID, which I'm not using.

**Comment by HenriBeck** [comment]
@shawnlauzon I would suggest having a look at our example Glitch server and using the code + library provided there.

https://github.com/aboutyou/dart_packages/tree/master/packages/sign_in_with_apple/sign_in_with_apple#server

**Comment by shawnlauzon** [comment]
@HenriBeck Yes, this is what I'm trying to do. 

The problem is this seems to have changed:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/611529/169671657-10778618-7916-4e11-adee-a73a56cf59ea.png">

1. It's Edit vs Configure
<img width="721" alt="image" src="https://user-images.githubusercontent.com/611529/169671665-b6c5de66-4611-4f5d-a500-af6c7c01a065.png">

2. There is no Return URL (the URL as described here seems to be different)
<img width="417" alt="image" src="https://user-images.githubusercontent.com/611529/169671675-7bbdeec7-2d50-4c87-88a6-08aa8606c9c1.png">

**Comment by shawnlauzon** [comment]
Ok, I've found a completely different way to validate what I get back from sign_in_with_apple. Previously I was trying to using `appleCredential.authorizationCode`. But instead of I use `appleCredential.identityToken` I can validate that on the server as a simple JWT using the instructions here: 

https://betterprogramming.pub/sign-in-with-apple-node-js-backend-implementation-for-ios-developers-25a54b79aa68

I assume this is just as good of a validation as using the authorization code that the Glitch server is using. Any thoughts?

**Comment by shawnlauzon** [comment]
Ahh, related question: the `identityToken` is declared as `String?`, unlike the `authorizationCode` which is a `String`. Can I not assume that I am given the JWT?

**Comment by HenriBeck** [comment]
@shawnlauzon the identity token is not always given though I'm not sure when exactly it is present or might be missing.

Overall we would recommend following the same code as the Glitch server since this exchanges the authorization code against a refresh token which then always contains the identity token
