### ISSUE TITLE
Getting only apple private mail

### ISSUE THREAD

**Issue by jnelle** [aboutyou/dart_packages#314]
Hi,

I configured everything like in this guide:
https://firebase.google.com/docs/flutter/setup?platform=ios

and used this code snippet and I'm only getting the generated private mails from apple.

https://firebase.google.com/docs/auth/flutter/federated-auth#apple

**Comment by alexislg2** [comment]
Dear @jnelle , why did you close this issue? I have the same problem

**Comment by alexislg2** [comment]
Dear @tp , I know that if the user chooses to use the private email, the server will only receive the private address, that makes 100% sense.

But in my case, the user is never asked wether he wants to use private or public email.

**Comment by mrvyas417** [comment]
YOU CAN get  both emails but only once, so either  you have to  handle them from the backend   or store them locally , I suggest you use the key chain

**Comment by alexislg2** [comment]
@mrvyas417 I see, that makes total sense

**Comment by mrvyas417** [comment]
@alexislg2  so if you are testing, and want the email again, then go to the settings> password & security > app using apple id> here your get app name  click on this and stop using apple id then try again, then you get an email again   
if you are using flutter then use this **flutter_keychain** and store , key chain sync with our apple account
