### ISSUE TITLE
[sign_in_with_apple] Revoke Token API/Account Deletion Requirement

### ISSUE THREAD

**Issue by dsgriffin** [aboutyou/dart_packages#316]
Per [Account deletion requirement iOS](https://developer.apple.com/news/?id=12m75xbj)

> If your app offers Sign in with Apple, you’ll need to use the Sign in with Apple REST API to revoke user tokens when deleting an account.

Are we able to utilise existing properties provided by this package to handle this? Or does it provide any helper methods? 

The following is not working as expected - any idea why?

```dart
final appleCredential = await apple.SignInWithApple.getAppleIDCredential(
  scopes: [
    apple.AppleIDAuthorizationScopes.email,
    apple.AppleIDAuthorizationScopes.fullName,
  ],
  nonce: nonce,
);

final credentials = new AppleCredentials(
  identityToken: appleCredential.identityToken!,
  credential: OAuthProvider("apple.com").credential(
    idToken: appleCredential.identityToken,
    rawNonce: rawNonce,
  ),
);

// revoke user token
await http.post(
  Uri.parse('https://appleid.apple.com/auth/revoke'),
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
  },
  encoding: Encoding.getByName('utf-8'),
  body: {
    "client_id": "example",
    "client_secret": appleCredentials.identityToken!,
    "token": credentials.accessToken!,
    "token_type_hint": "access_token",
  },
);
 ```

**Comment by HenriBeck** [comment]
> The following is not working as expected - any idea why?

Yes, the body you provide is wrong, especially the `client_secret`. The value there is only available on your server since it's a private key that you generate within the Apples Developer Portal.

@dsgriffin you should not call the API from the client since it requires the client's secret, which should never be leaked into your actual App. You need to implement this API on your server, which is also why this package will never offer such an API.

**Comment by brasizza** [comment]
Hi!, the problem is the apple now have a new guideline that obligate the software to have a revoke api in the app till 30th june. there is no other explanation about how to do it so we are a bit lost how to do this kind of thing

**Comment by HenriBeck** [comment]
@brasizza the implementation is in no way related to this library and fully happens on your server.

All of the explanations for the feature can be found in the documentation from Apple.
