### ISSUE TITLE
AppleIDAuthorizationScopes.fullName not included in UserCredential.user providerData

### ISSUE THREAD

**Issue by Theunodb** [aboutyou/dart_packages#317]
When signing in with apple the givenName and familyName should be included in the providerData displayName. See below use case. In our app we'll access the provider data *after* a successful sign in through the  authResult.user not through the credential thats not authenticated yet.

``` dart
  Future<User> signInWithApple({bool linkCredential = false}) async {
    try {
      String nonce = UtilitiesHelper.randomNonceString();
      AuthorizationCredentialAppleID credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        nonce: crypto.sha256.convert(utf8.encode(nonce)).toString(),
      );

      final AuthCredential authCredential = OAuthProvider('apple.com').credential(
        idToken: credential.identityToken,
        rawNonce: nonce,
      );

      UserCredential authResult = await firebaseAuth.signInWithCredential(authCredential);
      if (linkCredential) {
        return await linkWithCredential(authResult.credential!);
      } else {
        return authResult.user;
      }
    } on FirebaseAuthException catch (error) {
         print(error);
    } catch (error) {
      return TPFirebaseUser(null, error.toString(), null);
         print(error.toString);
    }
  }
```

**Comment by omarica** [comment]
A workaround is to manually update FirebaseAuth's CurrentUser object with the authCredential returned by Apple after the call to signInWithCredential()

`await firebaseAuth.currentUser?.updateDisplayName('${credential.givenName} ${credential.familyName}');
  return firebaseAuth.currentUser!; `

**Comment by HenriBeck** [comment]
@Theunodb this looks more of an issue with Firebase and not our library since you are accessing their property.
