### ISSUE TITLE
[sign_in_with_apple] Question: What is the difference between apple_sign_in and sign_in_with_apple package?

### ISSUE THREAD

**Issue by AndroidNils** [aboutyou/dart_packages#32]

**Comment by tp** [comment]
Hey @AndroidNils 

the major difference for the implementor is that this package also handles existing Safari/Keychain credentials on iOS. So if the user was ever logged into `yourwebsite.com` (and saved their password), they would not be prompted to create a new account with the Apple ID, but instead the calling app would receive the username/password combination, which they can then use to login.

Internally this is a slightly different implementation based on Swift.

I hope this answers your questions. Feel free to re-open if there is anything still open.
