### ISSUE TITLE
I am using giltch , how i logout , I using flutter

### ISSUE THREAD

**Issue by mrvyas417** [aboutyou/dart_packages#320]
I am using giltch , how i logout , I using flutter

_Originally posted by @mrvyas417 in https://github.com/aboutyou/dart_packages/issues/84#issuecomment-1170957453_

**Comment by emiliodallatorre** [comment]
> I am using giltch , how i logout , I using flutter
> 
> _Originally posted by @mrvyas417 in [#84 (comment)](https://github.com/aboutyou/dart_packages/issues/84#issuecomment-1170957453)_

That's not an issue of this repository, and therefore it should be closed.

**Comment by HenriBeck** [comment]
@mrvyas417 this is not something this plugin handles for you.

For a discussion, please see #84, but we don't offer any code/support beyond this.
