### ISSUE TITLE
'Hide My Email' Option Returning Null Value Instead of Proxy Email

### ISSUE THREAD

**Issue by tgritter** [aboutyou/dart_packages#324]
When I select the "Share My Email" option, the getAppleIDCredential() function successfully returns the email from my account

However, when I select "Hide My Email" the getAppleIDCredential() returns a null value. I believe it should be returning a proxy email instead of null value. 

Expected Result:
"Hide My Email" should be returning a proxy email

Actual Result: 
"Hide My Email" returns a null value

**Comment by tgritter** [comment]
I also tried on a brand new simulator, so it's not because I have already signed in on the device.

**Comment by HenriBeck** [comment]
@tgritter it has nothing to do with if you signed up on a specific device.

Apple will only provide the email once per account / app sign up, even if this happens on another device.  
To reset this you can de-authorize your App on the Apple ID website.

**Comment by tgritter** [comment]
@HenriBeck Actually I think the problem is the user needs to setup "Hide My Email" using their iCloud+ account. If they haven't set it up then "Hide My Email" will return a null value, which I'll need to reject on my end. Is that correct?
More info here: https://support.apple.com/guide/icloud/set-up-hide-my-email-mm9d9012c9e8/icloud

**Comment by tgritter** [comment]
Ahh, seems like I can get the email by parsing the identityToken. Oh Apple, there you go again making everything more complicated then it needs to be. Closing this issue.
