### ISSUE TITLE
Missing phrase in documentation

### ISSUE THREAD

**Issue by SharbelOkzan** [aboutyou/dart_packages#328]
On line 161 of the readme, it says 

>  - Likewise update the `signInWithAppleEndpoint` variable to point to your

to your what?

Sorry for opening such a trivial issue but I guess the missing word/phrase here could be important

**Comment by DanMossa** [comment]
This is actually the part I'm stuck on. I don't know what to put for this url

**Comment by HenriBeck** [comment]
This is related to our example app, correct?

You will want to point this URL to your server/endpoint, which will handle the authentication and create the session on your backend.  
In our example, this is just pointed to our example/dummy server to simulate this.
