### ISSUE TITLE
[sign_in_with_apple] Add support for Android via web API

### ISSUE THREAD

**Issue by AndroidNils** [aboutyou/dart_packages#33]

**Comment by tp** [comment]
@AndroidNils Would you like to have support for this, or would you also be willing to help out with this implementation?

Currently I am not sure if it could/should be handled entirely locally in a web-view, or if the library would need a (self-hosted?) login page which could open Chrome custom tabs (for easier login / credential sharing).

**Comment by AndroidNils** [comment]
> @AndroidNils Would you like to have support for this, or would you also be willing to help out with this implementation?
> 
> Currently I am not sure if it could/should be handled entirely locally in a web-view, or if the library would need a (self-hosted?) login page which could open Chrome custom tabs (for easier login / credential sharing).

I'd like to help. But unfortunately I don't have the time for it :(

**Comment by tp** [comment]
This has shipped with version 2.0.0.

We'll follow up with more integration information shortly, but for anyone familiar with the Apple docs and similar flows, this should be straightforward.

**Comment by tp** [comment]
Hey @AndroidNils,

I saw that you added SiwA on Flutter web here https://web.sharezone.net/

Did you use this package and just a modified server to communicate back to your website?

Would be interesting to document and support that flow as well for us :)

Thanks for any hints!

**Comment by AndroidNils** [comment]
Hi @tp,
currently we use `sign_in_with_apple` only for `macOS` and `iOS`. For web we use the `firebase_auth_oauth` package. Our backend service is Firebase authentication. We had a few problems with the web setup. I have to ask my teammate what exactly these problems were. I'll contact you again with the exact problems (If he still has them in his head) 👍

**Comment by AndroidNils** [comment]
@tp It was only an issue with the Firebase configuration (redirect url, etc.). But also my teammate don't no the exact problem 😬
