### ISSUE TITLE
getAppleIDCredential() stucks

### ISSUE THREAD

**Issue by keanallen** [aboutyou/dart_packages#330]
```dart
print('getting...');  // printing
final appleIdCredential = await SigninWithApple.getAppleIDCredential(
scopes: [
AppleIDAuthorizationScopes.email,
AppleIDAuthorizationScopes.fullName,
],
);
print(appleIdCredential );    // Not Printing

```

iPhone 11 Pro Max - iOS 15.5 

Also occurs in iOS 14

**Comment by hppyft** [comment]
I have the same problem on the emulator, they get stuck on the loading and never comeback.

**Comment by HenriBeck** [comment]
This is a known issue on the simulator which is not related to this plugin. 

For more information: #144
