### ISSUE TITLE
Cannot get email and full name

### ISSUE THREAD

**Issue by manhpv-1697** [aboutyou/dart_packages#331]
I can get email and full name for first time login. After that, credential only has authorizationCode, email, give name, family name are null
Deviece : Iphone 13 Pro Max / IOS : 15.6

**Comment by tp** [comment]
Yes, this is by (Apple's) design.

You need to store the fields you're interested in by yourself. Then on subsequent logins you can look them up by the user's ID.

**Comment by manhpv-1697** [comment]
yep, thanks !

**Comment by shubhamkislay** [comment]
What if the user deletes the account and then wants to recreate the account, in that case why would I be storing the email or full name. How to handle subsequent login for that?
