### ISSUE TITLE
[sign_in_with_apple] Special documentation for Firebase ?

### ISSUE THREAD

**Issue by quentin7b** [aboutyou/dart_packages#333]
Hi 

(And thanks for the package)

I followed the instructions to enable sing in with apple on both Android and iOS.
I am using Firebase to handle the OAuth workflow and there is a specific case.

While I was using this code to make it work

```dart

// First, generate a nonce
final charset = '0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._';
var nonce = List.generate(32, (_) => charset[Random.secure().nextInt(charset.length)]).join();

// Get apple credentials
var appleCredential = (Platform.isIOS)
    // On iOS, classic auth is working
    ? await SignInWithApple.getAppleIDCredential(
        scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
        ],
        // Give a hashed nonce
        nonce: sha256.convert(utf8.encode(nonce)).toString(),
    )
    // On Android, you need to go with web auth
    : await SignInWithApple.getAppleIDCredential(
        scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
        ],
        // Give a hashed nonce
        nonce: sha256.convert(utf8.encode(nonce)).toString(),
        webAuthenticationOptions: WebAuthenticationOptions(
            clientId: "THE SERVICE ID FROM APPLE DEV CONSOLE",
            redirectUri: Uri.parse('https://MY_PROJECT_ID.firebaseapp.com/__/auth/handler')
    )
);
var credential = OAuthProvider("apple.com").credential(
    idToken: appleCredential.identityToken,
    rawNonce: nonce,
);
```

It was working fine on iOS, but not on Android.
I was getting an error in the webview of sign in 

> Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.

Since with Firebase, there is a new way of doing this (which I know is specific) using [Federated Auth](https://firebase.google.com/docs/auth/flutter/federated-auth)

I had to replace everything by a simple line of code 

```dart
UserCredential credential = auth.signInWithProvider(AppleAuthProvider());
```

> No need to get `AuthCredential` before.

So, I know this is **not** a bug in your package ! It works fine.

But I wonder if, for those using firebase, maybe a point in the doc saying "If you are using firebase, please follow this doc" might be time saving ?

BTW, I've also commented on Firebase Repository https://github.com/firebase/flutterfire/issues/8865#issuecomment-1279681283

**Comment by HenriBeck** [comment]
> I was getting an error in the webview of sign in

That happens because the firebase auth handler is incompatible with us, and you would need a custom server for this.

If Firebase doesn't depend on our package anymore, that would be great. You can also post this solution in #91

**Comment by chadlyalan** [comment]
@HenriBeck I wouldn't have thought it a unique setup but I can't find documentation on a Flutter web app hosted on Firebase that successfully implements sign_in_with_apple. 
Do you know of any implementation guide for this setup?
