### ISSUE TITLE
Apple login in flutter run only one time but not working in second time and getting this error

### ISSUE THREAD

**Issue by Sayedmdkaif** [aboutyou/dart_packages#334]
AuthorizationAppleID(001745.849ed9d3f6414afabfa47794178d1a4f.1018, null, null, null, example-state).

**Comment by tp** [comment]
> 

This is working as designed by Apple. Subsequent "logins" (after the initial registration) return `null` for givenName, familyName, and email.

**Comment by Sayedmdkaif** [comment]
in the next login how it will work?

**Comment by HenriBeck** [comment]
@Sayedmdkaif you need to save these details on your server

**Comment by Sayedmdkaif** [comment]
after saving detail how to login next time?

**Comment by HenriBeck** [comment]
I would suggest reading into the topic on Apples Developer web or using Firebase to handle such things for you

**Comment by Sayedmdkaif** [comment]
could you please give me the link of topic on apple devleoper web

**Comment by HenriBeck** [comment]
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api
and
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple

**Comment by Sayedmdkaif** [comment]
are you sure this problem not come by using firebase?

**Comment by Sayedmdkaif** [comment]
any reply?

**Comment by tp** [comment]
> are you sure this problem not come by using firebase?

As said, this is by Apple's design to only return name & email on the initial sign up (also see the various questions about this here in the issue tracker). There is nothing the plugin can do here to help you there. It's the implementors responsibility to save that data somewhere if they want to retrieve it later (by the user account ID, which is always given in the `AuthorizationAppleID` class).

I don't see anything Firebase-related in the issue described, this will behave the same way no matter what backend you use.

Whether or not Firebase does support storing name & email and thus could help you in retrieving that data later on I don't know. All implementations I have seen use a in-house backend implementation.
