### ISSUE TITLE
Apple login not working in second time getting null values

### ISSUE THREAD

**Issue by Sayedmdkaif** [aboutyou/dart_packages#335]
i am having this error  AuthorizationAppleID(001745.849ed9d3f6414afabfa47794178d1a4f.1018, null, null, null, example-state).

The apple login worked only first time but in the second time getting above null values.

flutter doctor -v
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.19044.2130], locale en-IN)
    • Flutter version 3.3.3 on channel stable at G:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (4 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

**Comment by HenriBeck** [comment]
https://github.com/aboutyou/dart_packages/issues/334#issuecomment-1293181487
