### ISSUE TITLE
[sign_in_with_apple] Allow to request authentication without username/password

### ISSUE THREAD

**Issue by tp** [aboutyou/dart_packages#34]
In case Sign in with Apple returns saved keychain credentials (username/password) which are not valid on the backend the app should have the possibility to request login with an Apple ID (and ignore the saved credentials).

Otherwise this would lead to SiwA being stuck/not available to people who have old credentials in their keychain.

By providing this switch in the API, the app can decide whether to proceed with a "password reset" flow, or to create a new account based on the Apple ID.

**Comment by HenriBeck** [comment]
We should also allow specifying the scopes which are used for the apple sign in. Currently, those are hardcoded to both email and the full name, which might not be required for all apps.

**Comment by HenriBeck** [comment]
Closing this because we have split up the APIs
