### ISSUE TITLE
Please Add functionality for sign out apple OR don't retrun null value such as field like email, token, familyname, givenname etc when user second time sign in

### ISSUE THREAD

**Issue by insysinfo** [aboutyou/dart_packages#341]
Please Add functionality for sign out apple OR don't return as null value such as field like email, token, familyname, givenname etc when user second time sign in 

**getCredential using userIdentifier**
Otherwise pls should give one more function or method that if user pass on useridentifier in it, will return value email, token, familyname, givenname etc (when user second time sign in)

**Comment by tp** [comment]
This is just not possible with the APIs that Apple provides us.

The detailed user data is only returned on the initial sign up.

For signing out, this can either be done via the Settings app by the user, or from your end by revoking the Sign in with Apple token (https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens).  
Most apps already have implemented the latter as full account deletion (revoking the SiwA authentication + deleting all customer data) is now required by the App Store guidelines: https://developer.apple.com/news/?id=12m75xbj.

**Comment by insysinfo** [comment]
Thank you for given valuable answer :) @tp
