### ISSUE TITLE
sign_in_with_apple web error "Your request could not be completed due to an error. Please try again later." 

### ISSUE THREAD

**Issue by gurpreetSpiderWeb** [aboutyou/dart_packages#344]
Hello, 

I'm facing error "Your request could not be completed due to an error. Please try again later." (on attached screenshot) I have followed all the steps and retry many times 
Created a new apple ID for web app
Created a service ID
Created a key 
Setup glitch redirect URL 
Configure apple signin in service id
Setup the code (Screen shot attached)
I will be grateful if you can help me and point me right direction to resoled this issue, I'm unable to find issue.

<img width="734" alt="Screenshot 2022-12-09 at 1 12 56 PM" src="https://user-images.githubusercontent.com/109064060/206650839-f1bd6241-c59f-44d2-9497-7f0266a51cd2.png">
<img width="701" alt="Screenshot 2022-12-09 at 1 13 30 PM" src="https://user-images.githubusercontent.com/109064060/206650852-d0e22eb6-d8ab-4abc-b706-a197221cf2c1.png">

Thanks,
Gurpreet Singh

**Comment by veloso14** [comment]
It doesn't work for me @wenrong44333.
Any more ideias?

**Comment by veloso14** [comment]
I got it working it turns out @gurpreetSpiderWeb the browser is the problem and doesn't work on Chrome and Samsung

**Comment by hasnainhayat** [comment]
I'm facing same issue can you please help

**Comment by HenriBeck** [comment]
As stated, this can be a result of multiple things, e.g. a misconfiguration or also dependent on the browser since not every browser on Android devices supports `intent` links

**Comment by wenrong44333** [comment]
@hasnainhayat hi, is your issue still exist? If exist, you may contact me at wenrong44333@icloud.com, after we manage to solve the issue then we only post conclusion at here
