### ISSUE TITLE
Flutter sign in with Apple not working on iOS simulator (infinite loader)

### ISSUE THREAD

**Issue by Sayedmdkaif** [aboutyou/dart_packages#346]
I'm using [sign_in_with_apple](https://pub.dev/packages/sign_in_with_apple#server). Have an issue on iOS simulator (software version 13.0). Infinite loader is displayed after a password is entered and 'Continue' is tapped. The flow gets stuck. Nothing happens next. What could be the reason for that? What am I doing wrong?

And in real device when i run apple login it ran first time but login again gives these following error.14:26
 AuthorizationAppleID(001745.849ed9d3f6414afabfa47794178d1a4f.1018, null, null, null, example-state)
 1m 54s

✓] Flutter (Channel stable, 3.3.3, on macOS 11.6.1 20G224 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.3 on channel stable at /Volumes/SSDDATADRIVE/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (3 months ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kaif/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Volumes/data drive/Xcode.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • FECDF1FE-7B14-478F-8D2B-174490C2EEC1 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by tp** [comment]
There are multiple issues reported with the simulator. I don't know the exact details (always testing with real devices), but if you scan the issues here you'll see similar reports with various Xcode/iOS combinations.

> And in real device when i run apple login it ran first time but login again gives these following error.14:26
> AuthorizationAppleID(001745.849ed9d3f6414afabfa47794178d1a4f.1018, null, null, null, example-state)

This is not an error, but rather works as designed by Apple. You only get the auth token for subsequent logins, but not the name/email address (again). See the project documentation or issues for more details.

**Comment by RicharC293** [comment]
I had same issue and solve testing in simulator with iOS 16. before launch app I start my icloud session in settings

**Comment by mahdiyarz** [comment]
> I had same issue and solve testing in simulator with iOS 16. before launch app I start my icloud session in settings

I have the same issue with ios 17.5 in simulator, what do you mean you start your cloud session in settings before launch app?
