### ISSUE TITLE
name in identityToken

### ISSUE THREAD

**Issue by nurulhudaRizal** [aboutyou/dart_packages#355]
Hello,
Thank you for the package, i want to ask is it possible to get `name` in `identityToken`? because my system requires `name` inside identityToken.

Thank you

**Comment by HenriBeck** [comment]
@nurulhudaRizal if it's not there, we can't add it since the identify token comes from apple and not from the library.

**Comment by bernardoveras** [comment]
Same problem.

Name not found on token.
