### ISSUE TITLE
[sign_in_with_apple] Email '-'

### ISSUE THREAD

**Issue by mdmota** [aboutyou/dart_packages#357]
Some users are getting email = '-' , is this normal?

![image](https://user-images.githubusercontent.com/21266037/218578860-60a18f8c-7b9f-4511-91ec-0df808721247.png)

**Comment by HenriBeck** [comment]
@mdmota you are using a the firebase integration which may not be related to this package.

Please firs identify what you get back from our package and what you send to the firebase service to pin point the service that results in this behaviour.
