### ISSUE TITLE
[sign_in_with_apple] Unable to process request due to missing initial state...

### ISSUE THREAD

**Issue by ttb-inc** [aboutyou/dart_packages#367]
Hi

When I try to sign in to Apple on Android, I get the message below.
How can I get back to the app after authorization without the message below?

```
Unable to process request due to missing initial state.
This may happen if browser sessionStorage is inaccessible or accidentally cleared.
```

Thanks

**Comment by HenriBeck** [comment]
This is an issue with Apples website and not our plugin

**Comment by ttb-inc** [comment]
> 

Let's check it out.
Thanks.
