### ISSUE TITLE
[sign_in_with_apple] Can't get Web to work

### ISSUE THREAD

**Issue by JCKodel** [aboutyou/dart_packages#368]
I followed all the instructions and I'm using Glitch to handle Android web authentication.

It works fine on iPhone simulator and on Android Simulator, but in Web, the Apple Sign In pop-up is shown, everything is fine until the [Continue] button is clicked which does nothing.

Looking at devtools, after [Continue], a post is made to https://appleid.apple.com/appleauth/auth/oauth/authorize, it returns 200 with the access token, but nothing more happens.

How I need to configure or do to make it work for a Flutter web project?

**Comment by liyingte998** [comment]
能分享Glitch 代码吗

**Comment by jsmeke** [comment]
Happening also to me. The same issue.

**Comment by huseyinseyit** [comment]
I have the same problem, it does not return to the site on the apple side, when I press the continue button again and it gives the following error;
Your request could not be fulfilled due to an error. Please try again later.

**Comment by HenriBeck** [comment]
So you never see the request hit your configured redirect URL?

For any error on Apple's Website, we are not responsible.

**Comment by huseyinseyit** [comment]
> So you never see the request hit your configured redirect URL?

Yes, it doesn't go to the redirect URL at all. But mobile android and ios work, only the web does not work.
So there seems to be no problem on the redirect URL and apple side.

**Comment by JCKodel** [comment]
> So you never see the request hit your configured redirect URL?
> 
> For any error on Apple's Website, we are not responsible.

So, basically, is fuck off, right?

**Comment by HenriBeck** [comment]
> How I need to configure or do to make it work for a Flutter web project?

Please provide what you have configured in your code so far and on what domain you are calling the SiwA SDK.

**Comment by vanosidor** [comment]
Hi! Somebody fixed this? Have the same error =(

**Comment by jblankenship5** [comment]
Also have the same problem, No redirect after signing in successfully.
