### ISSUE TITLE
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.

### ISSUE THREAD

**Issue by Den-creator** [aboutyou/dart_packages#369]
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':sign_in_with_apple' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

**Need to upgrade kotlin version to version 1.6.20 and higher, as now it is not compilable even on NOT the latest grade (classpath 'com.android.tools.build:gradle:7.3.1').**

**Comment by HenriBeck** [comment]
@Den-creator could you please post the output of `flutter doctor -v`?

**Comment by Den-creator** [comment]
This issue is no longer reproduce
