### ISSUE TITLE
AuthorizationAppleID

### ISSUE THREAD

**Issue by MTEV** [aboutyou/dart_packages#381]
final credential = await SignInWithApple.getAppleIDCredential(
            scopes: [
              AppleIDAuthorizationScopes.email,
              AppleIDAuthorizationScopes.fullName,
            ],
          );

          print(credential);

give me  flutter: AuthorizationAppleID(001981.ca133b509db54bbaa9dc7a1a26d8798b.1404, null, null, null, null)
and not working 
credential!.email returen null

**Comment by HenriBeck** [comment]
in what terms is this not working?

**Comment by MTEV** [comment]
credential!.email returen null 
not returen any  thing

**Comment by HenriBeck** [comment]
that is normal and expected, see #334

**Comment by MTEV** [comment]
> that is normal and expected, see #334
It doesn't help

**Comment by MTEV** [comment]
> that is normal and expected, see #334
It doesn't help
why you. closed 
if you  don't. have answer please. don't  close  
thanks

**Comment by HenriBeck** [comment]
The answer is that this is expected and intended by Apple (not even our side).

You only get the email on the first login and you need to store this information on your server to retrieve it for subsequent logins.

**Comment by swayamshreecolourmoon** [comment]
> The answer is that this is expected and intended by Apple (not even our side).
> 
> You only get the email on the first login and you need to store this information on your server to retrieve it for subsequent logins.

Hi Henri, I faced the same issue. As you mentioned, Apple returns the username, etc., during the first-time login. I didn’t quite understand—what do you mean by "first-time login"? Does this refer to when a user tries to sign up after installing the application? Or does it also apply if an existing user uninstalls the application, reinstalls it, and then tries to log in with Apple? Is that the scenario you're referring to?

**Comment by swayamshreecolourmoon** [comment]
thanks @tp
