### ISSUE TITLE
[sign_in_with_apple] No givenName and familyName in Credentials object

### ISSUE THREAD

**Issue by mike392** [aboutyou/dart_packages#383]
Hi, Guys,

Can you, please, check why there is no familyName and givenName in the credentials response? Apple is insisting on pre-filling the information once being registered - thank you so much in advance!

```     
 try {
        appleCredential = await SignInWithApple.getAppleIDCredential(
          scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
          ],
          nonce: nonce,
        );
      } on SignInWithAppleException {
        return Future.delayed(Duration.zero);
      }

      // Create an `OAuthCredential` from the credential returned by Apple.
      final oauthCredential = OAuthProvider("apple.com").credential(
        idToken: appleCredential.identityToken,
        rawNonce: rawNonce,
      );
      print(appleCredential.givenName);
      print(appleCredential.familyName);
      ```

**Comment by MendleM** [comment]
Did you find a workaround?

**Comment by mike392** [comment]
> Did you find a workaround?

Unfortunately, no. Apple docs state that they send these fields ONLY when you do the first sign in via the app. From then on you have to save the info in SharedPreferences or something like that. This is how they API works - not the guilt of the plugin...
