### ISSUE TITLE
I got the error when am running the Xcode 15  , IOS 17.0 . How can I fix this issue.

### ISSUE THREAD

**Issue by vinodlee** [aboutyou/dart_packages#384]
Unhandled Exception: SignInWithAppleAuthorizationError(AuthorizationErrorCode.unknown, The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.))

**Comment by awaitANTHONY** [comment]
did you fixed it .?

**Comment by 2000calories** [comment]
try the solution here
https://stackoverflow.com/questions/59321233/com-apple-authenticationservices-authorization-error-code-1000/62897820#62897820

**Comment by HenriBeck** [comment]
@vinodlee is this issue only present on XCode 15 and iOS 17 and did it use to work before?
