### ISSUE TITLE
Integration of Apple signing with Firebase on Android is not working

### ISSUE THREAD

**Issue by dayerdl** [aboutyou/dart_packages#385]
i have the following code to signing with firebase

```
 Future<void> signInWithApple() async {
    try {
      WebAuthenticationOptions? authenticationOptions;
      if (!Platform.isIOS) {
        String redirectUri =
            "https://growth-app-50738.firebaseapp.com/__/auth/handler";
        String clientId = 'fit.growthapp';
        authenticationOptions = WebAuthenticationOptions(
            clientId: clientId, redirectUri: Uri.parse(redirectUri));
      }

      final rawNonce = _generateNonce();
      final nonce = _sha256ofString(rawNonce);
      final appleCredential =
          await SignInWithApple.getAppleIDCredential(scopes: [
        AppleIDAuthorizationScopes.email,
        AppleIDAuthorizationScopes.fullName,
      ], nonce: nonce, webAuthenticationOptions: authenticationOptions);

      final oauthCredential = OAuthProvider("apple.com").credential(
        idToken: appleCredential.identityToken,
        accessToken: appleCredential.authorizationCode,
        rawNonce: rawNonce,
      );

      final authResult =
          await FirebaseAuth.instance.signInWithCredential(oauthCredential);
      print("Vamos a ver jose ${authResult.user?.email}");

      // You can access the user information with authResult.user
    } catch (error) {
      print(error.toString());
    }
  }
```

The website to login appears and i can enter the password for my apple user. However when the login is completed i get this image

<img width="391" alt="Screenshot 2023-09-28 at 13 46 18" src="https://github.com/aboutyou/dart_packages/assets/1933760/ebd1c192-8bd7-4a82-bd67-027615bb8e46">

Any ideas?

**Comment by burak-kurtarir-epam** [comment]
> @dayerdl Why are you using this flow instead of the "default" one from the Firebase documentation, like
> 
> ```
>       final appleProvider = AppleAuthProvider()
>         ..addScope('email')
>         ..addScope('name');
> 
>       await FirebaseAuth.instance.signInWithProvider(appleProvider);
> ```
> 
> That worked well for me. I haven't tried a more "manual" Firebase integration as I think their SDK does already all the heavy lifting (and there is no need to integrate this package manually when using Firebase).

It worked for me. Thanks @tp
