### ISSUE TITLE
Sign in with Apple on iOS returns an invalid user token

### ISSUE THREAD

**Issue by hmirza1** [aboutyou/dart_packages#386]
Sign in with email/pass and google work perfectly but for some reason, sign in with apple gives me this output:

_Invalid user token detected, user is automatically signed out._

The output is only present if I ran the project in Xcode with an actual device. The simulator doesn’t show the error but my app behaves as if the user logs and an immediately logs out.

I followed all the instructions on the pub.dev package page.

This is my code for the sign in function:

```dart
Future<String?> registerWithApple() async {
try {
  final appleCredential = await SignInWithApple.getAppleIDCredential(
    scopes: [
      AppleIDAuthorizationScopes.email,
      AppleIDAuthorizationScopes.fullName,
    ],
  );

  final credential = OAuthProvider('apple.com').credential(
    idToken: appleCredential.identityToken,
    accessToken: appleCredential.authorizationCode,
  );

  try {
    // Sign in the user with Firebase
    await FirebaseAuth.instance.signInWithCredential(credential);
  } catch (fberr) {
    print('firebase error\n$fberr');
    return 'firebase error';
  }

  return 'Signed in with Apple';
} catch (err) {
  print(err);
  return 'Error';
}


}
``` 

Any help would be appreciated

**Comment by HenriBeck** [comment]
This is an issue with the Firebase Library and not ours. Please raise an issue on their Github Page
