### ISSUE TITLE
sign_in_with_apple is currently compiled against android-28.

### ISSUE THREAD

**Issue by guoheng1996** [aboutyou/dart_packages#391]
2 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.window:window-java:1.0.0-beta04' requires libraries and applications that
      depend on it to compile against version 31 or later of the
      Android APIs.

      :sign_in_with_apple is currently compiled against android-28.

      Recommended action: Update this project to use a newer compileSdkVersion
      of at least 31, for example 32.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.window:window:1.0.0-beta04' requires libraries and applications that
      depend on it to compile against version 31 or later of the
      Android APIs.

      :sign_in_with_apple is currently compiled against android-28.

      Recommended action: Update this project to use a newer compileSdkVersion
      of at least 31, for example 32.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

**Comment by SunryTeang** [comment]
before I have this problem too but currently solve it now
 just 

========build.gradle(app)==============
 android {
    namespace "com.example.test"
    compileSdk 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
========grandle-wrapper.propertiies=======================
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip

========build.gradle(android)==============
classpath 'com.android.tools.build:gradle:7.2.2'

all this work for me

**Comment by ankiimation** [comment]
> before I have this problem too but currently solve it now just
> 
> ========build.gradle(app)============== android { namespace "com.example.test" compileSdk 34 ndkVersion flutter.ndkVersion
> 
> ```
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_17
>     targetCompatibility JavaVersion.VERSION_17
> }
> 
> kotlinOptions {
>     jvmTarget = JavaVersion.VERSION_17
> }
> ```
> 
> ========grandle-wrapper.propertiies======================= distributionUrl=https://services.gradle.org/distributions/gradle-7.6.1-all.zip
> 
> ========build.gradle(android)============== classpath 'com.android.tools.build:gradle:7.2.2'
> 
> all this work for me

fixed by upgrade build:gradle to 7.x.x

**Comment by winter-tech** [comment]
I hope to upgrade the version of Kotlin on the Android side to 1.6.20 or higher. It is now 1.6.0, and some properties have a minimum of 1.6.20, so I cannot run it on the Android side.
