### ISSUE TITLE
Add iOS privacy manifests

### ISSUE THREAD

**Issue by a-yarimizu-dc** [aboutyou/dart_packages#414]
Hello,

In my project, we are working on supporting PrivacyManifest to meet the latest privacy requirements on iOS. 
Could you please confirm if there are plans to implement this support in the project?

I would appreciate any details regarding the plans and progress for implementing PrivacyManifest. Thank you for your consideration.

**Comment by stuartmorgan** [comment]
> Don't you think it might be necessary to place an empty manifest file even if you're not using the corresponding API? You can find more information on this from the following pages:
> [Apple Developer Documentation - Privacy Manifest Files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)

The yellow box on that page lists the situations in which an SDK needs to include a privacy manifest. There is currently no indication from Apple that most SDKs would require an empty manifest.

**Comment by HenriBeck** [comment]
Since we are not on the list that we need to include a manifest, we will close this issue for now
