### ISSUE TITLE
Facing issue in getting name in apple signin.

### ISSUE THREAD

**Issue by ahsanfarooq6414** [aboutyou/dart_packages#422]
here is the function in which I am trying to get apple credentials:
sign_in_with_apple: ^5.0.0
firebase_auth: ^4.12.1

Future signInWithApple() async {
    _hasError = false;
    notifyListeners();
    bool canAppleSignIn = await SignInWithApple.isAvailable();

    if (canAppleSignIn == true) {
      // executing our authentication
      try {
        final credential = await SignInWithApple.getAppleIDCredential(
          scopes: [
            AppleIDAuthorizationScopes.email,
            AppleIDAuthorizationScopes.fullName,
          ],
        );

        final oauthCredential = OAuthProvider("apple.com").credential(
          idToken: credential.identityToken,
        );
        final UserCredential userCredential = await FirebaseAuth.instance.signInWithCredential(oauthCredential);

        if (userCredential.user?.displayName == null ||
            (userCredential.user?.displayName != null && userCredential.user!.displayName!.isEmpty)) {
          final fixDisplayNameFromApple = [
            credential.givenName ?? '',
            credential.familyName ?? '',
          ].join(' ').trim();
          await userCredential.user?.updateDisplayName(fixDisplayNameFromApple);
        }
        if (userCredential.user?.email == null ||
            (userCredential.user?.email != null && userCredential.user!.email!.isEmpty)) {
          await userCredential.user?.updateEmail(credential.email ?? '');
        }

        user = FireStoreUser(
            email: userCredential.user?.email,
            imageUrl: userCredential.user?.photoURL ?? "https://winaero.com/blog/wp-content/uploads/2017/12/User-icon-256-blue.png",
            name: userCredential.user?.displayName,
            provider: "APPLE",
            uid: userCredential.user!.uid,
          );

        await saveDataToSharedPreferences();

        notifyListeners();
      } on FirebaseAuthException catch (e) {
        switch (e.code) {
          case "account-exists-with-different-credential":
            _errorCode =
                "You already have an account with us. Use correct provider";
            _hasError = true;
            notifyListeners();
            break;

          case "null":
            _errorCode = "Some unexpected error while trying to sign in";
            _hasError = true;
            notifyListeners();
            break;
          default:
            _errorCode = e.toString();
            _hasError = true;
            notifyListeners();
        }
      }
    } else {
      _hasError = true;
      notifyListeners();
    }
  }

**Comment by ahsanfarooq6414** [comment]
> Sorry, I don't have any experience with this kind of Sign in with Apple -> Firebase integration.
> 
> The common behavior with this plug-in people stumble upon is that the name is only provided for the initial sign-up (let's call it registration), and must then be stored in ones own data storage. From previous experience I know that the "default" Firebase SiwA integration does indeed save the user's name on their user object. Is it possible that you had different code running on the first login (= registration)? If so, try disassociating your Apple ID from the app and register anew.

No I am not using any other code for registering the user.

**Comment by ElvistLui** [comment]
It may be a Firebase's problem. I used FirebaseAuth before and was unable to obtain the user's email address, whether it was real or anonymous. I gave feedback to Firebase, and they replied that they are currently investigating the issue

**Comment by ahsanfarooq6414** [comment]
> It may be a Firebase's problem. I used FirebaseAuth before and was unable to obtain the user's email address, whether it was real or anonymous. I gave feedback to Firebase, and they replied that they are currently investigating the issue

please let me know if you find any solution regarding this issue thanks.

**Comment by HassanrazaBhatti** [comment]
@hajiboy95 some people have reported that on different other platforms that App Store is rejection applications with this solution can someone please confirm this ? and also can u send me complete code how are u managing first time sign in and second sign in in this case ?

**Comment by hajiboy95** [comment]
So in the end it worked quite easy for me. Now I have: 
```
Future<void> signInWithApple() async {
    try {
      final AppleAuthProvider appleProvider =
          AppleAuthProvider().addScope('name');
      cred = await FirebaseAuth.instance.signInWithProvider(appleProvider);
      await getUserData();
    } catch (error) {
      SnackBar(content: Text('Error signing in with Apple: $error'));
      debugPrint('Error signing in with Apple: $error');
      // Handle the error as needed in your application
    }
  }
```


where the getUserData() method is 
```
Future<void> getUserData() async {
    if (currentUser != null) {
      uData = await userDataRepository().getByID(currentUser!.uid);
      uData ??= userData(
          id: currentUser!.uid,
          name: cred?.user?.displayName,
          profile_picture_url: cred?.user?.photoURL,
          creation_date: cred?.user?.metadata.creationTime);
    } else {
      uData = null;
    }
  }
```

later on i use the uData for filling in the form. 
If apple complains i guess i'll just write a mail to them. so far it worked a few times to hand in my app (i didn't launched it yet, still in testing. but just sendet it a few times to apple to see whether they'll accept my method or not)

**Comment by askankit** [comment]
I was facing the same problem with Firebase auth here is how I solved it.


`  Future<UserModel?> _signInWithCredential(OAuthCredential oauthCredential, {String? userName, String? email, required String socialType}) async {
    try {
      final userCredential = await FirebaseAuth.instance.signInWithCredential(oauthCredential);
      final authUser = userCredential.user;
      if (authUser != null) {
        await authUser.updateProfile(displayName: userName,);
        await authUser.reload();
        final updatedUser = FirebaseAuth.instance.currentUser;
        return UserModel(
          social_id: updatedUser?.uid ?? authUser.uid,
          email: email ?? authUser.email,
          socialType: socialType,
          deviceToken: "No Device Token",
          name: updatedUser?.displayName ?? userName,
        );
      }else{
        return null;
      }
    } catch (e, s) {
      blocLog(msg: 'Sign-in with credential error: $e', bloc: "AuthServices", exp: s.toString());
      return null;
    }
  }`

**Comment by askankit** [comment]
I was facing the same problem with `FirebaseAuth`. The `displayName` was always `null` here is how you can fix it.

```dart
Future<UserModel?> _signInWithCredential(OAuthCredential oauthCredential, {String? userName, String? email, required String socialType}) async {
    try {
      final userCredential = await FirebaseAuth.instance.signInWithCredential(oauthCredential);
      final authUser = userCredential.user;
      if (authUser != null) {
        await authUser.updateProfile(displayName: userName,);
        await authUser.reload();
        final updatedUser = FirebaseAuth.instance.currentUser;
        return UserModel(
          social_id: updatedUser?.uid ?? authUser.uid,
          email: email ?? authUser.email,
          socialType: socialType,
          deviceToken: "No Device Token",
          name: updatedUser?.displayName ?? userName,
        );
      }else{
        return null;
      }
    } catch (e, s) {
      blocLog(msg: 'Sign-in with credential error: $e', bloc: "AuthServices", exp: s.toString());
      return null;
    }
  }

**Comment by itismejy** [comment]
appleCredential.givenName this is empty for me too
