### ISSUE TITLE
[sign_in_with_apple] 9 issues when building Flutter app in new Xcode 16.0

### ISSUE THREAD

**Issue by ghost** [aboutyou/dart_packages#437]
I have just installed the newly released macOS 15, and with that Xcode 16.0.

Upon trying to (re)build my code, I have noticed that even in the latest version of your `sign_in_with_apple` package, these 9 issues occur (in full):
<img width="782" alt="Screenshot 2024-09-17 at 7 47 38 PM" src="https://github.com/user-attachments/assets/0865ff47-496f-4aea-a717-a94cca3806ca">

This urgently requires your attention, since anybody who upgrades their MacBook is now unable to run or build their Flutter app if they use this package.

**Comment by 0x1306e6d** [comment]
As a workaround, I downgraded **Swift Language Version** to 5 and it works now for me.

<img width="499" alt="image" src="https://github.com/user-attachments/assets/e456d06e-0b14-423a-b83a-e00a2741fe04">

**Comment by appcapsergen** [comment]
> As a workaround, I downgraded **Swift Language Version** to 5 and it works now for me.

@0x1306e6d 
Thank you for your response, but your workaround does not work for me. Not sure if I'm doing something wrong, what were your steps to solve this exactly?
I will also wait for a response from the `sign_in_with_apple` team to resolve this for Swift 6.

**Comment by appcapsergen** [comment]
Thank you for the response and transparency @tp!
I will hopefully see the progress in this issue.

**Comment by 0x1306e6d** [comment]
> Thank you for your response, but your workaround does not work for me.
Not sure if I'm doing something wrong, what were your steps to solve this exactly?

I specified `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` to `YES` to address Firebase issue (https://github.com/firebase/flutterfire/issues/13323). Even so, I don't think it is related with this issue.

> I will also wait for a response from the sign_in_with_apple team to resolve this for Swift 6.

+1

**Comment by appcapsergen** [comment]
> I specified `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` to `YES` to address Firebase issue ([firebase/flutterfire#13323](https://github.com/firebase/flutterfire/issues/13323)). Even so, I don't think it is related with this issue.

Then I don't think the work-around works for everyone (aka not for me)

**Comment by gwhizofss** [comment]
> > Hi All, it looks like the podspec files for sign_in_with_apple have versions like 0.0.1. SHould those agree with the latest release 6.1.2?
> 
> Those do not matter, as dependencies are not published to Cocoapods, and thus only the `pub.dev` versions are visible to the consumer (without digging into the files). So we don't need to bump those `podspec`s with every release.

It's strange, when I leave it at 0.0.1 then the output of the build shows it is loading version 0.0.1. I'm on MacOS Sonoma. Should I open a new issue instead? BTW is the plugin supported when building on Macs with the M1 chip?

**Comment by gwhizofss** [comment]
> > Should I open a new issue instead?
> 
> No, I don't think we need to put any effort into this version. Even if `Pod` logs `0.0.1`, we know from the `pubspec.yaml` already what it actually is.
> 
> So unless it would now be a common pattern for iOS packages to bump the `Pod` spec file in unison with the `pubspec`, I would not do that.
> 
> We'll be working on SPM support next anyway, as `Pod`s are on the way out (though we will still support them for a long time going forward).
> 
> > BTW is the plugin supported when building on Macs with the M1 chip?
> 
> Yes, works fine for me :)

Can I suggest updating the documentation/comments that it is not for x86 only, but can work on M* with Rosetta2?

**Comment by appcapsergen** [comment]
@tp I can run my app again with `v6.1.3-dev1`!

**Comment by appcapsergen** [comment]
@tp actually, false positive 😅 
I forgot to use Swift 6 in my project. Without selecting this for the Pod's, my app works again, but as soon as I specify Swift 6, I get the following Swift Compiler Error's:
```console
Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:)' in a synchronous nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:39:35

Swift Compiler Error (Xcode): Call to main actor-isolated instance method 'performRequests(requests:)' in a synchronous nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:44:29

Swift Compiler Error (Xcode): Call to main actor-isolated static method 'parseRequests(rawRequests:)' in a synchronous nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:45:65

Swift Compiler Error (Xcode): Reference to var 'FlutterMethodNotImplemented' is not concurrency-safe because it involves shared mutable state
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:100:19

Swift Compiler Error (Xcode): Main actor-isolated property 'systemName' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:47

Swift Compiler Error (Xcode): Main actor-isolated class property 'current' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:39

Swift Compiler Error (Xcode): Main actor-isolated property 'systemVersion' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:78

Swift Compiler Error (Xcode): Main actor-isolated class property 'current' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:70
```

**Comment by appcapsergen** [comment]
@tp what about the errors I showed with Swift 6?

**Comment by HenriBeck** [comment]
@appcapsergen this sounds like: https://github.com/flutter/flutter/issues/150388#issuecomment-2174576564

Did you already enable the strict concurrency setting?

**Comment by HenriBeck** [comment]
Nevermind, the Flutter issue read a bit like as if this was also a setting for Swift 6 that can be controlled.

> But I haven't found any general information on this regarding Flutter, and also current examples on the latest Flutter stable (3.24.3) still generate code similar to this package's.

Since that is the case, I think we need to wait a little here to get some guidance from the Flutter Team on how to write plugins using Swift 6.

**Comment by appcapsergen** [comment]
@tp I'm sure I will be able to run the example app and even my app, because what I meant is the following;

In my app, in the `Podfile`, I specify a few build settings for all pods, including `SWIFT_VERSION`:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SWIFT_VERSION'] = '5.10' # <<<<<<<<--------- over here
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
```

So what I meant is that if I set the Swift version for pods with `config.build_settings['SWIFT_VERSION'] = '6.0'`, I do still get the following errors in the `sign_in_with_apple` package:
```console
Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:)' in a synchronous nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:39:35

Swift Compiler Error (Xcode): Call to main actor-isolated instance method 'performRequests(requests:)' in a synchronous nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:44:29

Swift Compiler Error (Xcode): Call to main actor-isolated static method 'parseRequests(rawRequests:)' in a synchronous nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:45:65

Swift Compiler Error (Xcode): Reference to var 'FlutterMethodNotImplemented' is not concurrency-safe because it involves shared mutable state
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleAvailablePlugin.swift:100:19

Swift Compiler Error (Xcode): Main actor-isolated property 'systemName' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:47

Swift Compiler Error (Xcode): Main actor-isolated class property 'current' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:39

Swift Compiler Error (Xcode): Main actor-isolated property 'systemVersion' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:78

Swift Compiler Error (Xcode): Main actor-isolated class property 'current' can not be referenced from a nonisolated context
/Users/sepekerimu/.pub-cache/hosted/pub.dev/sign_in_with_apple-6.1.3-dev1/ios/Classes/SignInWithAppleError.swift:31:70
```

**Comment by appcapsergen** [comment]
@tp great timing, but yes indeed that was the (or one of the) problem(s).

I am honestly not sure why I've done this in my project as I did this ages ago. Considering to remove this line since it does appear to be unnecessary!
