### ISSUE TITLE
[sign_in_with_apple] Resolve pending call when Chrome Custom Tab closes

### ISSUE THREAD

**Issue by tp** [aboutyou/dart_packages#46]
It should be possible to get notified when the Chrome Custom Tab activity closes, but I didn't find the relevant API on the v2 Android / Flutter embedding.

https://stackoverflow.com/questions/41010017/callback-on-dismiss-of-chrome-custom-tabs/41444238#41444238

**Comment by HenriBeck** [comment]
@tp I think we would need to use the https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityPluginBinding.html#addActivityResultListener-io.flutter.plugin.common.PluginRegistry.ActivityResultListener-
to listen to those events. I can quickly try that out later today

**Comment by tp** [comment]
Done in #88 🥳
