### ISSUE TITLE
Integration with Firebase Auth

### ISSUE THREAD

**Issue by miguelpruivo** [aboutyou/dart_packages#62]
Hi,

Thank you for the package. I need to integrate this with Firebase Auth (using oAuth2) and unfortunately, the `AuthorizationCredentialApple` doesn't have the `idToken` that I need in order to get a valid `AuthCredential`. 

Do you know a way to get it or isn't currently unsupported?

Thanks!

**Comment by HenriBeck** [comment]
In practice, this should be possible.

I just saw that we are not exposing the `identityToken` anymore. I think we didn't see an immediate use case before, but we can definitely add the token back.

I guess we would also need to support the `nonce` for all platforms to enable Firebase Auth to work.

But other than that this should be possible.

**Comment by miguelpruivo** [comment]
@HenriBeck thanks for the fast response. Any clue of when this might be added?

Thanks.

**Comment by HenriBeck** [comment]
I think adding those two features shouldn't be hard. I will provide two PRs now, and they should be released until EOW

**Comment by HenriBeck** [comment]
The PRs have been created. I only need to check android if we are getting the identity token there

**Comment by HenriBeck** [comment]
@miguelpruivo I just validated that the identity token works on Android, so I think both PRs are finished. We will probably not be able to test the integration with Firebase ourselves at the moment.

**Comment by miguelpruivo** [comment]
@HenriBeck no problem, I’ll test it myself on iOS side and let you know. Thanks for the quick implementation!

**Comment by HenriBeck** [comment]
@miguelpruivo We have released version 2.1.0 with `nonce` and `identityToken` support.

This should be all the work that is needed on our site; therefore I will close this ticket. If you encounter any other integration issues, please let us know.

**Comment by miguelpruivo** [comment]
Thank you @HenriBeck!

**Comment by tp** [comment]
@miguelpruivo Did this solve your issue? In #73 there is another question of how to integrate Firebase auth, so it would be super helpful if you could share your code if it's working for you now, so we could add that as an example here.

Thanks 🙏
