### ISSUE TITLE
点击取消按钮，苹果登录框会再次弹出来，

### ISSUE THREAD

**Issue by ZHanOBa** [aboutyou/dart_packages#74]
调起苹果登录（不是授权弹出框），点击弹出框的取消按钮，弹出框会向下弹出，过1秒又弹出来了（重复一次），再次点击取消按钮，就取消掉了弹出框，这是什么问题？？？

**Comment by HenriBeck** [comment]
Hey, please post your question in English. For now, I will close this ticket and reopen it once the question has been posted in English.
