### ISSUE TITLE
Add state field in SignInWithApple._signInWithAppleAndroid and in WebAuthenticationOptions

### ISSUE THREAD

**Issue by alberto-ferrini** [aboutyou/dart_packages#77]
According to https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms and https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple , the _Required Query Parameters_ could contains the _step_ parameter, useful for sending additional data to the server component.

**Comment by HenriBeck** [comment]
We should also support the `state` on iOS and macOS then.

https://developer.apple.com/documentation/authenticationservices/asauthorizationopenidrequest
https://developer.apple.com/documentation/authenticationservices/asauthorizationappleidcredential

**Comment by HenriBeck** [comment]
@alberto-ferrini I put up a small PR that implements this. I haven't had time to test this yet though; maybe I can find some time over the weekend to make sure this works as expected.

If you need this before, feel free to pull that specific branch in your project. If you do, I would appreciate some feedback if this works as expected.

#78

**Comment by HenriBeck** [comment]
@alberto-ferrini We have released version `2.2.0` with the `state` parameter support
