### ISSUE TITLE
[sign_in_with_apple] AppleAuth Error on Glitch example server

### ISSUE THREAD

**Issue by dtheodor79** [aboutyou/dart_packages#80]
Tried to test signing in with Apple from an Android device as described, however the glitch server responds with an AppleAuth Error:

```
(node:4047) UnhandledPromiseRejectionWarning: AppleAuth Error – Error occurred while signing: Error: error:0909006C:PEM routines:get_name:no start line

(node:4047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:4047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Looks like that the key contents are not well formatted, so in server.js I replaced 

`process.env.KEY_CONTENTS.replace(/\|/g, "\n"),`
with
`process.env.KEY_CONTENTS.replace(/\\n/gm, '\n'),`
when creating the AppleAuth, which fixes the problem.

Should it be updated in the example server as well?

**Comment by HenriBeck** [comment]
I think when we set up the example, we replaced all `\n` in the private key with `|` and then replaced them again when running the code.

I can't recall the exact reasoning behind this; I think @tp maybe knows more here.

If you do `.replace(/\\n/gm, '\n')`, then you also don't need to`replace` at all, because you are essentially replacing `\n` with `\n`.

**Comment by tp** [comment]
My reason was that I couldn't place a multi-line string into the Glitch config (which is just an .env-like file). Hence the `|` workaround…

I see that there is (now) a graphical editor for the config, so maybe that works better when pasting the full file in there:
![image](https://user-images.githubusercontent.com/52437/82727814-11eabc80-9ced-11ea-9c7c-fae26f38b5f8.png)

I will retest that later. For now I have fixed the comment (which said to use `\n`, when one should use `|`).

**Comment by dtheodor79** [comment]
I was playing around with different replacement approaches, then (after hours) this worked. :)

I guess now this issue can be closed.

If you want me to open it again for any reason, let me know.

**Comment by 571cky** [comment]
Igual por aca. Me da los mismos errores.
