### ISSUE TITLE
sign_in_with_apple: Set aud claim so identityToken works with Firebase Auth on Android

### ISSUE THREAD

**Issue by nickmeinhold** [aboutyou/dart_packages#94]
I followed the instructions to get Sign In With Apple working on Android and seem to have the whole flow working, to the point of getting a credential from `SignInWithApple.getAppleIDCredential`.  However when I try to use the credential to sign in with Firebase, as in: 

```Dart
final credential = OAuthProvider(providerId: 'apple.com').getCredential(
    idToken: appleIdCredential.identityToken,
    accessToken: appleIdCredential.authorizationCode,
);
```

The JWT seems to use the Service Id (entered in the clientId parameter of WebAuthenticationOptions) for the `aud` claim but Firebase Auth expects the `aud` claim to have the Firebase project id.  The error message is: 

> The supplied auth credential is malformed or has expired. [ The audience in ID Token [com.example.project.auth-service] does not match the expected audience com.example.project. ]

**Comment by HenriBeck** [comment]
@nickmeinhold Have you tried changing your service id to be `com.example.project`? I can't remember if that was possible to have the same service id + app bundle ID

**Comment by HenriBeck** [comment]
Also, you can just change the service ID in Firebase auth to match the one you have in your Flutter code

**Comment by nickmeinhold** [comment]
Thanks for the response @HenriBeck 

I can't change the service id to be `com.example.project` as that is already used as the identifier for my App Id and errors when I try to change it. 

When you say "change the service ID in Firebase auth" do you mean the firebase project Id?  I could create a new project and move everything over I guess... is that what you're suggesting?

**Comment by nickmeinhold** [comment]
@HenriBeck did you mean to close this?  I don't think it's been resolved.

**Comment by HenriBeck** [comment]
@nickmeinhold I will post a screenshot of what I mean later. And yeah I meant to close this as it's probably a misconfiguration in your Firebase project itself.

When you setup Sign in with Apple, you also give firebase the `clientId` and I think you gave the wrong one when you did the initial setup.

**Comment by nickmeinhold** [comment]
I spent a lot of time trying to be sure it wasn't my mistake in setting things up, and maybe it was but it feels very dismissive to not have a chance to respond before the issue is closed.  

I followed your documentation for the clientId, it seems quite clear to me.  

```sh
The developer’s client identifier, as provided by WWDR.

This is the Identifier value shown on the detail view of the service after opening it from https://developer.apple.com/account/resources/identifiers/list/serviceId Usually a reverse domain notation like com.example.app.service
```

As I said, I can't change the Service Id identifier to what Firebase Auth is expecting (which is the firebase project id) because my App Id identifier already uses the same value. 

If the plugin will aways produce an id token with an `aud` claim with the value passed in to `clientId` and that can't be changed then I think it would be good to add something to the docs to that effect, maybe as a note for people trying to use the plugin with firebase auth, or just somewhere so people like me know to stop trying to figure it out.  

I'd have been happy to put up some doc PRs or try and help in some way, I'm not meaning to use this as a helpdesk, but rather trying to help improve the excellent open source software you've made.

**Comment by nickmeinhold** [comment]
My apologies @HenriBeck , I was misunderstanding what you were saying, you were absolutely right it was a problem with my configuration, I imagine the screenshot you were going to add was something like this one: 

<img width="656" alt="Screen Shot 2020-06-09 at 2 00 36 am" src="https://user-images.githubusercontent.com/1059276/84053737-b2332780-a9f5-11ea-811a-526b06f1c187.png">

Sorry for taking up your time.

**Comment by HenriBeck** [comment]
@nickmeinhold yeah, that the exact screenshot I wanted to send.

**Comment by tp** [comment]
> I'd have been happy to put up some doc PRs or try and help in some way, I'm not meaning to use this as a helpdesk, but rather trying to help improve the excellent open source software you've made.

@nickmeinhold Thanks for pulling through. As Firebase integration is a common question here, a PR documenting the steps (and potential pitfalls) would be much appreciated 🙇🏻‍♂️

**Comment by nickmeinhold** [comment]
@tp OK great, will do - I really appreciate the help getting it working so happy to contribute something. Thanks!
